rmm/armv9a/src/exception/trap.rs, rmm/armv9a/src/exception/trap/syndrome.rs, rmm/armv9a/src/helper/mod.rs, rmm/armv9a/src/helper/regs.rs, rmm/armv9a/src/lib.rs, rmm/armv9a/src/realm/mm/page_table/pte.rs, rmm/armv9a/src/realm/mm/stage2_translation.rs, rmm/armv9a/src/rmi/realm.rs, rmm/armv9a/src/rsi/mod.rs
1. Change the scope of s2tlb sync to inner sharable
2. [Temporary] Share realm data pages with nw
3. Add RSI for granule change. Initial submission.
Will use event handler as rmi does.
=> Realm page update

third-party/README.md, third-party/worktree.toml
├── third-party
│   ├── android-kernel (android12-5.10 kernel)
│   ├── gki-build (kernel build configs) 
gki-build> BUILD_CONFIG=../android-kernel/build.config.gki.aarch64 build/build.sh
=> add android kernel worktree

scripts/init.sh, scripts/tests/tf-a-tests.sh
This PR fixes previous CI failed
- Add error handling
- Remove open-jdk-11
- Increase timeout value
=> Fix CI build failed

scripts/init.sh
=> Fix ci failure about dependency

rmm/armv9a/src/realm/registry.rs, rmm/monitor/src/realm/mod.rs, rmm/monitor/src/realm/vcpu.rs, rmm/monitor/src/rmi/mod.rs, rmm/monitor/src/rmi/realm/mod.rs, rmm/monitor/src/rmi/realm/rd.rs, rmm/monitor/src/rmi/rec/mod.rs, rmm/monitor/src/rmi/rtt.rs
redefine realm and vcpu(==rec) state according to ARM spec.
=> update RMI handlers for realm intialization

examples/confidential-ml/device/device.cc, examples/confidential-ml/device/run_gui.sh, examples/confidential-ml/device/run_gui_fl.sh, examples/confidential-ml/runtime/run_gui.sh, examples/confidential-ml/runtime/runtime.cc
This PR adds functions for "device" and "runtime server" to interact with node-js web servers. Web servers work like a mirroring server. Putting it all together, they work in the following order. (in ML scenario)
1. <web browser - host machine> takes input from users and passes it on to "device".  (from chat-bot like UI)
2. <device - CCA> do inference and sends back the prediction to the web server.
3. <web browser - host machine> gets the prediction and shows it on the browser. (to chat-bot like UI)
4. <device - CCA> sends the correct answer to the runtime server.
5. <runtime - host machine>  do training with the correct answer and send the newly trained model to the device.
- I need to update a docker image to include this PR and the customized codes of the node-js web server. (chat-bot …
=> add functions to interact with nodejs server for better outlook

.gitmodules, realm/linux-rsi/.gitignore, realm/linux-rsi/.gitmodules, realm/linux-rsi/Makefile, realm/linux-rsi/rsi.c, realm/linux-rsi/rsi.h, realm/linux-rsi/rsictl/.cargo/config.toml, realm/linux-rsi/rsictl/.rustfmt.toml, realm/linux-rsi/rsictl/Cargo.toml, realm/linux-rsi/rsictl/build.rs, realm/linux-rsi/rsictl/lib/token_verifier/attest_defines.h, realm/linux-rsi/rsictl/lib/token_verifier/token_dumper.c, realm/linux-rsi/rsictl/lib/token_verifier/token_dumper.h, realm/linux-rsi/rsictl/lib/token_verifier/token_verifier.c, realm/linux-rsi/rsictl/lib/token_verifier/token_verifier.h, realm/linux-rsi/rsictl/src/ioctl/kernel.rs, realm/linux-rsi/rsictl/src/ioctl/mod.rs, realm/linux-rsi/rsictl/src/lib.rs, realm/linux-rsi/rsictl/src/main.rs, realm/linux-rsi/rsictl/src/subcmds.rs, realm/linux-rsi/rsictl/src/token/dumper.rs, realm/linux-rsi/rsictl/src/token/mod.rs, realm/linux-rsi/rsictl/src/token/verifier.rs, realm/linux-rsi/rsictl/src/token_c/mod.rs, realm/linux-rsi/rsictl/src/tools.rs
Simple `make` inside the linux-rsi will compile both, the
module (rsi.ko) and the command line tool (rsictl) and put them both
inside the $ROOT/out/shared directory to be used within the realm.
Then inside the realm:
mount -t devtmpfs none /dev
cd /shared
insmod rsi.ko
./rsictl attest
=> linux-rsi merge

examples/confidential-ml/code_model.md, examples/confidential-ml/common/socket.cc, examples/confidential-ml/common/socket.h, examples/confidential-ml/device/device.cc, examples/confidential-ml/runtime/runtime.cc, examples/confidential-ml/word_model.md
- update README.md to have how to test with a browser-based GUI.
- make GUI interaction more stable (previously, I used 'netcat' utility for interaction between browser and apps, but it didn't work often.. I don't know why.. so, I ended up replacing 'netcat' with a simple C socket program.
- [Docker image](https://github.com/Samsung/islet/releases/tag/example-confidential-ml-v1.1) update
=> demo-gui improvement

examples/confidential-ml/code_model.md
This `code_model.md` and the docker image is going to be shared with vmware.
=> update code_model.md in accordance with the current docker image

doc/book.toml
This PR fixes the book title from `ILSET` to `ISLET`.
=> Fix the book title

README.md, doc/components/attestation.md, doc/components/certifier.md
- update a video of confidential ml --> I wanted to embed either GIF or MP4 directly in README.md, but when I did it, github said "something went wrong"...
- fix minor TODOs in md files (fix links)
=> Update Confidential ML video

rmm/monitor/src/event/rsihandle.rs, rmm/monitor/src/rmi/rec/handlers.rs, rmm/monitor/src/rmi/rec/mod.rs, rmm/monitor/src/rmi/rec/run.rs, rmm/monitor/src/rmi/rtt.rs, rmm/monitor/src/rsi/mod.rs, rmm/monitor/src/rsi/psci.rs
update rsi event handler parameter
Record requests with RSI_IPA_STATE_SET and its results from RTT_INIT_RIPAS in Rec struct.
Move handlers in rec/mod.rs to rec/handlers.rs
=> Rsi set ripas

rmm/armv9a/src/exception/trap.rs, rmm/armv9a/src/gic.rs, rmm/armv9a/src/helper/mod.rs, rmm/armv9a/src/helper/regs.rs, rmm/armv9a/src/realm/context.rs, rmm/armv9a/src/realm/mod.rs, rmm/armv9a/src/realm/registry.rs, rmm/armv9a/src/realm/timer.rs, rmm/monitor/src/rmi/mod.rs, rmm/monitor/src/rmi/rec/handlers.rs, rmm/monitor/src/rmi/rec/run.rs
1. Support realm timer at RMM
2. Deliver write value to the normal world on mmio data abort
=> Realm timer support

doc/SUMMARY.md, doc/crates/index.md, doc/platform-development/index.md, doc/platform-development/secure-interaction.md, doc/usecases/index.md
- create a new page that describes "secure interactions with the host".
- and kind of attempts that have to do with "secure coding practices in ISLET RMM" should be added in github pages. (e.g., verification stuff in the furture?)
=> update page for `secure interactions with the host`

scripts/deps/pkgs.sh
This PR adds packages for Ubuntu 22-04.
I tried by WSL(Windows Subsystem for Linux).
=> scripts: Add apt packages for Ubuntu 22

rmm/monitor/src/mm/error.rs, rmm/monitor/src/rmi/gpt.rs, rmm/monitor/src/rmi/realm/mod.rs, rmm/monitor/src/rmi/rec/handlers.rs, rmm/monitor/src/rmi/rtt.rs, rmm/monitor/src/rmm/granule/mod.rs
This PR is a minor refactoring about error handling
=> Refactor granule error handling

rmm/armv9a/src/helper/asm.rs, rmm/armv9a/src/rmm/mod.rs
This PR can fix #146 by dcache-flush
=> dcache flush to fix the problem that reads dummy value

sdk/Cargo.toml, sdk/Makefile
This PR sidesteps the issue https://github.com/Samsung/islet/issues/159 to avoid a build error.
=> sdk: Replace .so file

scripts/fvp-cca, scripts/tests/acs.sh
This PR update acs's test script
- Add timeout value
- Check expected passes cases
I tried to add this script to CI, but it makes hang. (CI runner & docker too)
I raise it to an issue. https://github.com/Samsung/islet/issues/187
=> scripts: Update acs test

.github/workflows/ci.yml, Dockerfile, scripts/deps/pkgs.sh, scripts/docker/build.rs, scripts/docker/run.rs, scripts/fvp-cca, scripts/tests/acs.sh
This PR fixes https://github.com/Samsung/islet/issues/187.
_The cause of the issue is same with https://github.com/Samsung/islet/issues/176. 👍_
=> ci: Add ACS Test

.github/workflows/ci.yml, scripts/deps/pkgs-for-ci.sh, scripts/deps/rust_min.sh, scripts/init_min.sh, scripts/init_min_acs.sh, scripts/init_min_tf_a.sh, scripts/tests/realm-boot.sh
This PR fixes the [ci issue](https://github.com/Samsung/islet/issues/195). `apt update` has been changed to `apt-get update`. The duplicate file will be removed in the later time (it was used to avoid a cache issue in workflow).
=> ci: Fix the issue regarding not found

.github/workflows/ci.yml
This PR uploads logs to CI artifacts
=> ci: Upload ACS test artifacts

README.md, doc/dev-dependencies.md
- High-level architecture diagram and introduce Islet HES in README.md.
- Separate the dependencies column into Build time and Runtime in  dev-dependencies.md.
=> doc: update documents

scripts/configure_tap.sh
- don't set default route for the host
- fix setting ip forward for non privileged user
=> Fix host network configuration

doc/dev-site.md
I deployed https://github.com/islet-project/islet/pull/259 to our developer site.
And this PR guides to deploy our developer site.
=> doc: Add "How to deploy Dev Site"

doc/SUMMARY.md, doc/usecases/index.md, scripts/make_doc.sh
This PR adds cross-platform e2ee example to dev-site.
Please refer [this](https://islet-project.github.io/islet/usecases/cross-platform-e2ee.html).
=> doc: Add cross-platform e2ee to dev-site

examples/veraison/accept-all.rego, examples/veraison/bootstrap.sh, examples/veraison/provisioning/run.sh, examples/veraison/veraison-no-auth-patch
This PR updates Veraison to the latest version and provides a script to bootstrap Veraison with correct config and patches.
It requires: https://github.com/islet-project/remote-attestation/pull/3
=> Update to the latest Veraison version

rmm/src/rsi/hostcall.rs
This PR refactors `rsi::HostCall`
- Deleted 4 unsafe blocks(1 method, 3 inner blocks)
- Added the width checking according to RMM spec
_Now `rsi::Hostcall` is also the target of Autopadding https://github.com/islet-project/islet/issues/276_
=> refactor: rsi: Fix to add padding instead of union

rmm/src/rmi/realm/params.rs
See [comment](https://github.com/islet-project/islet/pull/287#discussion_r1533282578) for detail
=> Revert "rmi: remove padded fields on hash calculation"

plat/fvp/memory.x
This PR refactor the linker script
- Fix indentation
- Remove manual address computation using hex number
- Add the memory layout description
=> Refactor the linker script
