islet-project/islet

.github/workflows/ci.yml
scripts/tests/tf-a-tests.sh
third-party/worktree.toml

- Now CI do 'cargo check` 
- If third-party projects updated, we need to update `worktree.toml` too. 
- Please refer https://github.com/Samsung/islet/commit/a367b4f866f93e796136329dc285eef5d4dde238
- This processes, commit check, on `init.sh`

Enable cargo check to CI & bump 3rd-nw-linux to latest

---

README.md
realm/linux/Makefile
realm/wasm/Makefile
realm/wasm/README.md
scripts/config.py
scripts/fvp-cca

This PR supports wasm runtime on realm. 
The wasm-realm is composed with `wasmer` and `linux kernel`.
`wasmer` is statically built into rootfs for linux.
The reason why i choose this combo is that noted at https://github.com/Samsung/islet/issues/26.
- wasmer: v3.1.4
- kernel: v5.19
- Wasm-fs is located in `islet-asset`
- Change naming `vm` to `realm` to avoid confusion between normal world vm and realm vm.
- RMM spec does not use `realm vm` too.

Support wasm runtime as a realm

---

scripts/.config
scripts/config.py
scripts/fvp-cca
third-party/worktree.toml

This PR applies [tip](https://trustedfirmware-a.readthedocs.io/en/latest/components/realm-management-extension.html) to make boot & run linux faster.
> Tips to boot and run Linux faster on the FVP :
> Set the FVP option cache_state_modelled to 0.
> Disable the CPU Idle driver in Linux either by setting the kernel command line parameter “cpuidle.off=1” or by disabling the 
> CONFIG_CPU_IDLE kernel config.
- optee-build is updated to add a kernel command line option : https://github.com/Samsung/islet/commit/977f2f228bf790b08ed0ef5ce0d811f7cad27109
- minor refactor on `fvp-cca` script

Make boot & run linux faster on fvp

---

scripts/config.py
scripts/fvp-cca
third-party/worktree.toml

1. Build aosp image sperately.
2. Place the results, combined-ramdisk.img and system-qemu.img, into ${islet}/out with new names, initrd-aosp.img and system-qemu-aosp.img respectively.
3. Build aosp kernel for fvp. 
./scripts/fvp-cca -bo -nw linux

script: add aosp build nw

---

scripts/fvp-cca
third-party/worktree.toml

- common-android-mainline tagged `android-mainline-6.2`
- based on android-mainline-6.2 
- merged 28 commits from linux-cca (based on linux-6.2 rc1)
- check the build and results.

add android-kernel-6.2 worktree

---

scripts/config.py
scripts/fvp-cca
third-party/worktree.toml

- Update android-kernel-6.2 to b8859291c271, enabling v9fs (`CONFIG_9P_FS`)
- Share `out/aosp_data` by 9p
- Add `--no-prebuilt-initrd` option

third-party: Update android-kernel

---

rmm/armv9a/src/realm/registry.rs
rmm/monitor/src/lib.rs
rmm/monitor/src/rmi/features.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/realm/params.rs
rmm/monitor/src/rmi/version.rs

This PR
--------
- Support RMI_FEATURES and RMI_REC_AUX_COUNT.
- Add `RmiRealmParams` and parsing logic
Added two RMIs are called before creating realm.
`realm_create()` of tf-a-tests is passed with this PR.
Issue
------
RealmParams is passed from NS.
RMM cannot access the memory about RealmParams now (GPF).
To avoid this issue temporarily, mark the memory as REALM before the access there.
Current RMI status is noted at https://github.com/Samsung/islet/issues/48

Support RMI_FEATURES and RMI_REC_AUX_COUNT

---

third-party/worktree.toml

This PR imports [Certifier](https://github.com/vmware-research/certifier-framework-for-confidential-computing)

third-party: Import Certifier project

---

scripts/sync-worktree.py
third-party/README.md

This PR replace error to warning messages.
1. Fork the third-party branch to another branch (ex. 3rd-nw-linux-XXXXXX)
2. Add patches and test
3. Update `third-party/worktree.toml` and make pull-request

third-party: Emit messages when HEAD is mismatched

---

rmm/board/fvp/memory.x
rmm/board/fvp/src/main.rs
rmm/monitor/src/event/mainloop.rs
rmm/monitor/src/event/mod.rs
rmm/monitor/src/lib.rs
rmm/monitor/src/rmi/features.rs
rmm/monitor/src/rmi/gpt.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/rec/mod.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmi/version.rs
third-party/worktree.toml

1. Make the event handle loop(mainloop) extensible. previous:
Handler(context, rmi, smc, ...);
- All member objects of Monitor are delivered as arg.
- Adding new features to monitor requires changes to Handler param. i.e., All existing listeners have to be modified to add the new param. now:
Handler(context, monitor);
2. Place the event registration to mainloop and remove overlay functions. mainloop does the actual work in run(). previous: monitor simply calls run to make mainloop start its work. now: directly call run() in mainloop at main().

change relationship between monitor and mainloop

---

rmm/armv9a/src/exception/trap.rs
rmm/monitor/src/event/mainloop.rs
rmm/monitor/src/event/mod.rs
rmm/monitor/src/event/realmexit.rs
rmm/monitor/src/event/rsihandle.rs
rmm/monitor/src/lib.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/realm/rd.rs
rmm/monitor/src/rmi/rec/mod.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rsi/hostcall.rs
rmm/monitor/src/rsi/mod.rs

Required data struct to process RSI
1. Context: prepared at the REC_ENTER handle routine to place an RSI request.
2. monitor to access smc (e.g., for measurement), RmmPagetable for IPA_STATE_SET and so on.
3. struct 'Run' to place RSI specific output.

rsi: process RSI through an event handle routine

---

README.md
docs/examples.md
docs/network.md
scripts/config.py
scripts/configure_tap.sh
scripts/fvp-cca
scripts/fvp/launch-realm-net.sh

This PR enables a full networking support for ARM FVP, which means that a Realm running on top of ARM FVP can interact with PC Host that launches ARM FVP, via ethernet.
For detail of its network configuration, see `docs/network.md`.
Commits that this PR relies on:
- [islet-asset](https://github.com/Samsung/islet-asset/commit/207217312f6cd2eda64ce3bc3ff86a05f1488ab4)
- [3rd-optee-build-230407](https://github.com/Samsung/islet-asset/commit/207217312f6cd2eda64ce3bc3ff86a05f1488ab4)

Enable network

---

rmm/armv9a/src/rmm/mod.rs
rmm/armv9a/src/rmm/translation.rs
rmm/monitor/src/mm/page_table/mod.rs
rmm/monitor/src/rmi/gpt.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/rec/mod.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmm/granule.rs
rmm/monitor/src/rmm/mod.rs
rmm/monitor/src/smc.rs

#61 
1. not map the memory and deleted param_ptr and such as rmi::REALM_CREATE
2. some parameters were setted from Undelegate to Rec(others) such as rmi::REC_CREATE
-> if parsing parameter can be removed, it doesn't need to map the memory anymore. 
1. find_granule 
2. set_state
normally, 
when state set the **RD, Rec, RecAux, Data** state
address will be **mapped** on Rmm page
when state set the **Delegate** state
address will be **unmapped** on Rmm page

add granule structure for memory region state

---

rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/version.rs

I found that `rmi::ABI_VERSION = 1` reflects "minor version" only. To encode "major and minor version" properly in the result register, they must be encoded in a way of `encode_version()`.

encode ABI version considering both major and minor

---

sdk/build.rs
sdk/include/islet.h
sdk/src/c_api.rs

This PR 
- adds `islet_status_t` to handle error status
- notes license to the header reviewed here => (https://github.com/vmware-research/certifier-framework-for-confidential-computing/pull/68)

sdk: Add islet_status_t to handle error

---

arch/arm64/kernel/rsi.c

They are required for linux-rsi driver working as out of tree module.

Add static variables for RSI in kernel address space

---

rmm/monitor/src/rmi/gpt.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/rec/mod.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmm/granule.rs
scripts/config.py
scripts/fvp-cca

1. Increase granule covered space for fvp dram1
2. remove find_granule unwrap() 
3. add RMI_DATA_DESTROY

expand granule region for fvp dram

---

.github/workflows/ci.yml
README.md
scripts/build-acs.sh
scripts/config.py
scripts/deps/pkgs.sh
scripts/fvp-cca
scripts/tests/acs.sh
third-party/worktree.toml

This PR
- adds [ACS; Architecture Compliance Suite](https://github.com/ARM-software/cca-rmm-acs) for RMM as a third-party project
- add a test script ~~and attaches it to CI~~
We use ACS's version 0.7 and it needs some patches to test easily.
Please refer [cca-rmm-acs branch](https://github.com/Samsung/islet/tree/3rd-cca-rmm-acs-230531)
```
$ scripts/tests/acs.sh 
[!] Building realm management monitor...: tf-rmm
[!] Building ACS...
[!] Building bootloaders(bl1.bin, fip.bin)... 
REGRESSION REPORT: ................
==================
TOTAL TESTS     : 59
TOTAL PASSED    : 41
TOTAL FAILED    : 16
TOTAL SKIPPED   : 2
TOTAL SIM ERROR : 0
******* END OF ACS *******
```
or you can test directly like
```sh
$ scripts/fvp-cca --normal-world=acs --rmm=tf-rmm
```

Add ACS test

---

docs/network.md
examples/confidential-ml/code_model.md
scripts/configure_tap.sh
scripts/fvp-cca
scripts/fvp/configure-net.sh

- With this PR, FVP Host and Realm are able to communicate through PC_Host's network to remote hosts. (I tested it with a command `wget http://49.247.7.63/` to see if it can download index.html in the remote server)
- But, this has been only confirmed in wired network not wireless network. I'll test the same thing again on wireless, once a new laptop gets available for the demo.
- To enable remote networking, there must be at least one real IP address required. (previously, we only used dummy IP address for local networking, which would be better for testing purpose)
- I think it would definitely be better to have two different networking options, (1) remote networking and (2) local networking (good enough for testing purpose), and local networking is going to be a default option.

Enable networking between Realm and remote hosts

---

cli/README.md
doc/SUMMARY.md
doc/components/attestation.md
doc/components/cca_design.md
doc/components/certifier.md
doc/getting-started/app-dev.md
doc/getting-started/cca.md
doc/getting-started/debug_realm.md
doc/getting-started/plat-dev.md
doc/network.md
doc/usecases/confidential_ml.md
examples/confidential-ml/README.md
examples/confidential-ml/word_model.md
sdk/README.md

This PR fixes typos some of which were found with `aspell`. I've also removed or modified seemingly incorrect sentences.

doc: Fix typos and misleading sentences

---

rmm/armv9a/src/gic.rs
rmm/armv9a/src/helper/regs.rs
rmm/armv9a/src/lib.rs
rmm/armv9a/src/realm/context.rs
rmm/armv9a/src/realm/registry.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/rec/mod.rs
rmm/monitor/src/rmi/rec/run.rs

This PR is intended for enabling interrupt support in Realms.
According to the specification, a virtual Generic Interrupt Controller (vGIC) should be presented to a Realm in order for the Realm to use interrupts. The vGIC is implemented via a combination of Host emulation and RMM mediation. For the RMM mediation, this commit restores and saves the interrupt context on REC entry and exit by communicating with the Host.
Reference: Realm Management Monitor specification (Chapter A6. Realm interrupts and timers) and [TF-RMM](https://github.com/TF-RMM/tf-rmm).

Add support for GIC

---

rmm/armv9a/src/helper/regs.rs
rmm/armv9a/src/realm/registry.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rec/run.rs

This PR helps to handle the Memory-mapped I/O (MMIO) accesses by Realms. When a Realm accesses device's registers using MMIO, it causes a data abort which was the main reason for the kernel stuck. In this PR, RMM receives the emulated value from the Host (nw-linux) and injects the value to the Realm after setting the Realm's PC value to the next point. With these fixes, the guest kernel in the Realm now could boot to the next stage.
Reference: Arm Armv9-A Architecture Registers and TF-RMM
[before]
```
...
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0              <-- no more log after this point
```
[after]
```
...
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[ …
```

rmm: Add support for mmio handling

---

rmm/monitor/src/host/mod.rs
rmm/monitor/src/host/pointer.rs
rmm/monitor/src/lib.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/realm/params.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rec/params.rs

The goal of this PR is to define a common way to access **physical region allocated by the host** (i.e., shared between the host and the rmm) in a secure manner.
All places that use `ManuallyDrop` have to do with that physical region. So, to replace `ManuallyDrop`, it's required as a groundwork to define that interface.
- relevant issue:  #107 
`struct Pointer` in host/pointer.rs is HostPointer which points to the physical region. To securely map and access that region, this PR uses Rust's guard pattern.
`struct PointerGuard` is a guard for `Pointer`. Only when all security checks are passed, it can get this guard and thus dereference the original pointer. 
See code comments for more detail.
To securely access different kinds of `HostPointer`, this PR defines `Accessor` trait.
Any structs …

Introduce HostPointer and Accessor

---

rmm/armv9a/src/exception/trap.rs
rmm/armv9a/src/exception/trap/syndrome.rs
rmm/armv9a/src/helper/mod.rs
rmm/monitor/src/rmi/rec/handlers.rs

1. Add exception handlers for wfi and wfe in armv9a/src/exception/trap.rs
2. Disable TWI in HCR_EL2 (trap to EL2) and add warning message to the REC_ENTER requests in case that the normal world wants to set it enabled.
- current design decision: I don't see a good reason we support per realm or per realm execution configuration with TWI in HCR_EL2. It is more feasible setting enble or disable for all realms consistently.
- As current linux-cca in normal world does not handle wfx exceptions, just disable it. We currently have exception handler for wfx.  When we need such dynamic configuration in the future, let's add the hcr_el2 context management then.

Wfx exception handle

---

rmm/monitor/src/host/mod.rs
rmm/monitor/src/host/pointer.rs
rmm/monitor/src/lib.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rec/run.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmm/granule.rs

- Introduce `HostPoinerMut` which are used to access "mutable physical host region".
- `HostPointer` is used for
- Params for REALM_CREATE
- Params for REC_CREATE
- Source data page for DATA_CREATE
- `HostPointerMut` is used for
- Run  (it needs to be mutable to handle RSI. e.g., HOST_CALL handler modifies Run)
- Note
- Rec/Rd/Data(target_data)/... --> those that involve granule states should be handled in a different way than `HostPointer`. I'll do update codes to manage those struct in a separate PR that might have to do with #113 .
- Related issue: #107 
- #112 
- #113    --> this issue is likely the next to go
- #114

Apply HostPointer and HostPointerMut

---

rmm/armv9a/src/helper/mod.rs

This PR enable ACS with islet-rmm.
This PR applied a workaround to run. _I added comment the reason._
```rush
./scripts/fvp-cca -nw=acs
```
Check `out/uart0~1.log`
https://github.com/Samsung/islet/issues/108

Enable ACS with islet-rmm

---

rmm/armv9a/src/realm/registry.rs
rmm/monitor/src/event/mainloop.rs
rmm/monitor/src/event/mod.rs
rmm/monitor/src/event/rsihandle.rs
rmm/monitor/src/host/pointer.rs
rmm/monitor/src/rmi/error.rs
rmm/monitor/src/rmi/features.rs
rmm/monitor/src/rmi/gpt.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmi/version.rs
rmm/monitor/src/rsi/mod.rs
rmm/monitor/src/rsi/psci.rs

This PR enhances the RMI's error handling with the following having in mind:
- unify the error value with the common one similar to `TF-RMM`
- propagate the error with Rust's try (`?`) operator
- set the return value in one place, not in the middle which could miss setting the value (`RMI_ENTER` is an exceptional case)

Improve RMI's error handling

---

.github/workflows/ci.yml

This PR fixes the [CI failure](https://github.com/Samsung/islet/issues/124) temporarily which was caused by the space limitation (500MB).
[the related log]
```
Caused by:\n failed to unpack `windows_i686_gnu-0.48.0/lib/libwindows.0.48.0.a` into `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_i686_gnu-0.48.0/lib/libwindows.0.48.0.a`\n\n 
Caused by:\n No space left on device (os error 28)\n" }))', sdk/build.rs:36:10
```

ci: Disable linux-cca workflow

---

rmm/monitor/src/host/mod.rs
rmm/monitor/src/host/pointer.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rec/params.rs
rmm/monitor/src/rmi/rec/run.rs
rmm/monitor/src/rmi/rtt.rs

To avoid concurrency issues in accessing NS space, this PR introduces `copy_from/to_host_or_ret!()` macros that do
1. map host memory 
2. copy from/to host memory to RMM stack memory that is bound to each CPU.
3. unmap host memory
NOTE:  I'll add documents into our github page (about secure coding(?) --> these macros + RMI command validation)
TODO:  check if the granule state of the phyiscal addr is Undelegated. --> this is specified in the RMM spec.
I'll do it in https://github.com/Samsung/islet/pull/121, as this PR has to do with granule state.
```
pub trait Accessor {
fn acquire(ptr: usize, page_map: PageMap) -> bool {
// TODO: check if the granule state of `ptr` is Undelegated.
page_map.map(ptr, false)
}
}
```

introduce copy_from/to_host_or_ret!() to avoid concurrency issues

---

rmm/armv9a/src/smc.rs
rmm/monitor/Cargo.toml
rmm/monitor/src/event/mod.rs
rmm/monitor/src/macro.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rsi/mod.rs

It was hard to check RSI/RMI logs. The main reason is the flow of RMI. We should call smc first with `REQ_COMPLETE` to handle RMI.
Make rmi/rsi logging more pretty.
```
[TRACE]armv9a::smc -- cmd[C400018F], args[0], ret[C4000151, 88435000, 0, 0, 0, 0, 0, 0]
[TRACE]armv9a::smc -- cmd[C40001B0], args[88435000], ret[0, 88435000, 0, 0, 0, 0, 0, 0]
[TRACE]armv9a::smc -- cmd[C400018F], args[0], ret[C4000151, 88438000, 0, 0, 0, 0, 0, 0]
[TRACE]armv9a::smc -- cmd[C40001B0], args[88438000], ret[0, 88438000, 0, 0, 0, 0, 0, 0]
[TRACE]armv9a::smc -- cmd[C400018F], args[0], ret[C4000151, 8843B000, 0, 0, 0, 0, 0, 0]
```
```
[TRACE]monitor::event -- RMI: RTT_INIT_RIPAS       [88C00000, 88B3D000, 3] > [0, 0]
[TRACE]monitor::event -- RMI: GRANULE_DELEGATE     [88B3D000] > [0]
[TRACE]monitor::event -- RMI: …
```

rmm: Refactor rmi/rsi logging

---

rmm/monitor/src/event/mainloop.rs
rmm/monitor/src/event/mod.rs
rmm/monitor/src/rmi/error.rs
rmm/monitor/src/rmi/version.rs

Fixed https://github.com/Samsung/islet/issues/129
This PR fixes to encode `error code` to `x0` properly.

Fix smc context bug

---

rmm/monitor/src/rmi/rec/mod.rs

- This PR fixes #118 .
- In-depth analysis for this bug is [here](https://github.com/Samsung/islet/issues/118#issuecomment-1650894030).
- While debugging this issue, I came across a new issue, #131 , which needs to be handled in the future.
- Plus, we need to have a secure way to manage Rd/Rec/Data/... . They could be handled via #112 .

initialize Rec.ripas by zero (fix fdt bug)

---

rmm/armv9a/src/realm/mm/stage2_translation.rs
rmm/armv9a/src/realm/registry.rs
rmm/monitor/src/event/mainloop.rs
rmm/monitor/src/event/mod.rs
rmm/monitor/src/event/rsihandle.rs
rmm/monitor/src/realm/mm/mod.rs
rmm/monitor/src/rmi/gpt.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmm/granule/mod.rs
rmm/monitor/src/rmm/granule/translation.rs
rmm/monitor/src/rsi/mod.rs
toolchains

This PR covers negative TCs related RMI_GRANULE_DELEGATE.
1. Change GranuleState to Delegated with PA translated by IPA given RMI 
2. Handle RMI_ERROR_INPUT according to RMM Spec
3. Set granule state only when un/delegation succeed
| idx | type | addr |
|:---:|:---:|:---:|
|1| ADDR_UNALIGNED| 0x88300001|
|2| ADDR_DEV_MEM_MMIO| 0x1C0B0000|
|3|ADDR_OUTSIDE_OF_PERITTED_PA| 0x1000000001000|
|4| ADDR_DELEGATED| 0x8830C000|
|5| ADDR_REC| 0x88315000|
|6| ADDR_DATA| 0x88348000|
|7| ADDR_RTT| 0x88306000|
|8| ADDR_RD| 88303000|
|9| ADDR_PAS_REALM| 8834E000|
|10| ADDR_PAS_SECURE| 6000000|

acs: Pass granule delegation case

---

rmm/armv9a/src/realm/mm/stage2_translation.rs
rmm/monitor/src/mm/page_table/mod.rs
rmm/monitor/src/rmm/granule/entry.rs
rmm/monitor/src/rmm/granule/mod.rs
rmm/monitor/src/rmm/granule/translation.rs

This is an interim implementation of `get_granule_state()` for ACS works that @bitboom is working on.
This implementation will likely be modified in a future PR that deals with #112.
See `test_get_granule_state()` to know how to use i.t

add get_granule_state()

---

rmm/monitor/src/lib.rs
rmm/monitor/src/macro.rs
rmm/monitor/src/rmi/realm/params.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rec/params.rs

This PR
- removes `unsafe & ManuallyDrop`
- adds tests for spec compliance
`Unsafe & ManuallyDrop` was introduced by union type. (the way of tf-rmm implement) 
I change this by adding padding.
---
I will apply this way to other structures continuously

Remove unsafe & ManuallyDrop about shared data structrues 

---

rmm/armv9a/src/rmm/page_table/attr.rs
rmm/armv9a/src/rmm/translation.rs
rmm/monitor/src/event/mainloop.rs
rmm/monitor/src/rmi/gpt.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/realm/rd.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmm/granule/entry.rs
rmm/monitor/src/rmm/granule/mod.rs

This PR covers negative TCs related RMI_GRANULE_UNDELEGATE.
I have recorded the ACS status to https://github.com/Samsung/islet/issues/149
1. Manage RTT pages
2. Fix mem attributes of shared pages for RMI -> detach cache issue https://github.com/Samsung/islet/issues/146
| idx | type | addr |
|:---:|:---:|:---:|
|1| ADDR_UNALIGNED| 0x88300001|
|2| ADDR_DEV_MEM_MMIO| 0x1C0B0000|
|3|ADDR_OUTSIDE_OF_PERITTED_PA| 0x1000000001000|
|4| ADDR_UNDELEGATED| 0x8830C000|
|5| ADDR_REC| 0x88315000|
|6| ADDR_DATA| 0x88348000|
|7| ADDR_RTT| 0x88306000|
|8| ADDR_RD| 88303000|

acs: Pass granule undelegation cases

---

rmm/monitor/src/host/mod.rs

This PR is intermediate status of `realm creation`. 
I share this PR to disable cache state modelling temporarily.

Validate PA before copy from host to realm

---

rmm/monitor/src/rmi/constraint.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/rtt.rs

ACS status with this PR,
```
REGRESSION REPORT:
==================
TOTAL TESTS     : 59
TOTAL PASSED    : 6
TOTAL FAILED    : 48
TOTAL SKIPPED   : 2
TOTAL SIM ERROR : 3
```
The following tests have newly passed with this PR.
```
cmd_rmi_version
cmd_rsi_version
cmd_realm_config
cmd_ipa_state_get
```
This result has been updated to #149 .

support RMI_RTT_UNMAP_UNPROTECTED

---

lib/rsi-el0/Cargo.toml

This PR fixes build errors in ci (compatibility issue).

sdk: rsi-el0: Fix build errors in recent nix (0.27)

---

rmm/armv9a/src/realm/registry.rs
rmm/monitor/src/realm/mod.rs
rmm/monitor/src/rmi/features.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/realm/mod.rs
rmm/monitor/src/rmi/realm/params.rs

This PR covers negative TCs related RMI_REALM_CREATE.
- Add validation logic of realm_params and features_reg_0
- Prevent double locking => Raise https://github.com/Samsung/islet/issues/162
- Manage vmid
| idx | type |
|:---:|:---:|
|1| PARAMS_UNALIGNED |
|2| PARAMS_DEV_MEM |
|3|PARAMS_OUTSIDE_OF_PERMITTED_PA |
|4| PARAMS_PAS_REALM |
|5| PARAMS_PAS_SECURE |
|6| HASH_ALGO_INVALID TA|
|7| HASH_ALGO_UNSUPPORTED |
|8| RTT_BASE_RD_ALIASED |
|9| RD_UNALIGNED |
|10| RD_DEV_MEM  |
|11| RD_OUTSIDE_OF_PERMITTED_PA |
|12| RD_STATE_UNDELEGATED |
|13| RD_STATE_RD |
|14| RD_STATE_REC |
|15| RD_STATE_RTT |
|16| RD_STATE_DATA |
|17| RTT_UNALIGNED |
|18| FEAT_REG_INVALID |
|19| RTT_START_INVALID |
|20| RTT_BASE_UNDELEGATED  |
|21| VMID_INVALID |
|22| VMID_USED |

acs: Pass realm creation cases 

---

rmm/monitor/src/rmi/features.rs

This PR resolves https://github.com/Samsung/islet/issues/163. The previous check did not consider the case when FEAT_LPA2 is implemented and caused a failure in realm linux booting.

rmm: Remove an invalid feature check

---

rmm/armv9a/src/config.rs
rmm/armv9a/src/exception/trap.rs
rmm/armv9a/src/realm/mm/mod.rs
rmm/armv9a/src/realm/mm/page_table/entry.rs
rmm/armv9a/src/realm/mm/stage2_translation.rs
rmm/armv9a/src/realm/mm/stage2_tte.rs
rmm/armv9a/src/realm/registry.rs
rmm/armv9a/src/rmm/page_table/entry.rs
rmm/armv9a/src/rmm/translation.rs
rmm/monitor/src/mm/page_table/mod.rs
rmm/monitor/src/realm/config.rs
rmm/monitor/src/realm/mm/mod.rs
rmm/monitor/src/realm/mod.rs
rmm/monitor/src/rmi/constraint.rs
rmm/monitor/src/rmi/mod.rs
rmm/monitor/src/rmi/rec/handlers.rs
rmm/monitor/src/rmi/rec/mod.rs
rmm/monitor/src/rmi/rtt.rs
rmm/monitor/src/rmm/granule/entry.rs
rmm/monitor/src/rmm/granule/mod.rs
rmm/monitor/src/rmm/granule/translation.rs
rmm/monitor/src/rsi/mod.rs
scripts/fvp-cca
scripts/tests/tf-a-tests.sh

This PR enables realm to use virtio (e.g., file system access) by allowing shared pages to be accessed by the Host. With this PR, realm-linux will be able to boot to the shell with islet.
Realm can modify its private region into a shared region by invoking `RSI_IPA_STATE_SET` with RIPAS:empty (Figure D2.1 Realm shared memory protocol flow in rmm-spec). With the following `RMI_RTT_SET_RIPAS`, this triggers a set of actions by the Host (e.g., `RTT_SET_RIPAS`->`RTT_READ_ENTRY`->`DATA_DESTROY`) according to the value of RTT entry for freeing regions (For more about detail, please refer to realm_tear_down_rtt_range() in nw-linux). This PR fills this flow. 
`linux-cca` controls the accesses to the encrypted/decrypted page with the bit 33 in Realm's page table entry (the bit location can be …

Add support for virtio

---

rmm/armv9a/src/realm/registry.rs

This PR fixes https://github.com/Samsung/islet/issues/167
* Spec 3.4.22 RmiStatusCode type RMI_ERROR_RTT: An RTT walk terminated before reaching the target RTT level, or reached an RTTE with an unexpected value.

rmi: Fix RMI_ERROR_RTT condition

---

scripts/deps/pkgs.sh

bzip2 is needed to build `initrd`

scripts: Add bzip2 to pkgs dependency

---

lib/armv9a/src/regs.rs
rmm/src/lib.rs
rmm/src/mm/page_table/entry.rs
rmm/src/mm/translation.rs
rmm/src/realm/mm/page_table/entry.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/registry.rs

1. For RMM S1 page table
- It's important to set attribute index porpery for both rmm memory and uart
- Re-enable cacheability in SCTLR_EL2
2. For Realm S2 page table
- change cachability properties to NORMAL_FWB
Note: 
The purpose of this PR is only correcting the cache properties in page table descriptors.
there is redundancy between stage2_tte.rs and translation_granule_4k.rs. This is out of scope of this PR.

rmm: correct cache settings

---

rmm/src/rmi/realm/mod.rs
rmm/src/rmi/realm/params.rs
rmm/src/rmi/realm/rd.rs
rmm/src/rmi/rtt.rs
scripts/fvp-cca

This PR passes `whole realm activate cases` & `some data creation cases`.
The rest of data creation cases are related with `RTT walk`.
_@zpzigi754 is fixing about `RTT walk` now, so I will re-visit after his work :)_
The main patches of this PR are two
- Validate whether IPA, passed by host, is in PAR.
- Because IPA of Realm should be in PAR(Protected Address Range)
- Implement `REALM_ACTIVATE`

acs: Pass whole realm activate cases  & some data creation cases

---

rmm/src/granule/mod.rs
rmm/src/host/pointer.rs
rmm/src/rmi/realm/rd.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rmi/rec/mpidr.rs
rmm/src/rmi/rec/params.rs
rmm/src/rmi/rtt.rs

This PR passes 35/36 in REC_CREATE by
-  Validate `rmi arguments` and `rec params` in REC_CREATE
-  Add RmiRecMpidr
- Add rec_index to RD
Failed case is related with `B3.4.11 RmiRecCreateFlags`.
The reserved fields of `RmiRecCreateFlags` must be zero.
But when i patched it like spec, it makes failures of other cases. 
tf-rmm is also failed in this case.
I need more analysis of this case.

acs: Pass 35/36 rec creation cases 

---

doc/dev-dependenices.md

| Name                  | Type       | License           | URL                                                 |
| --------------------- | ---------- | ----------------- | --------------------------------------------------- |
| bitflags              | runtime    | MIT/Apache-2.0    | https://github.com/bitflags/bitflags                |
| cc                    | build time | MIT OR Apache-2.0 | https://github.com/rust-lang/cc-rs                  |
| hashbrown             | runtime    | MIT OR Apache-2.0 | https://github.com/rust-lang/hashbrown              |
| lazy_static           | runtime    | MIT/Apache-2.0    | https://github.com/rust-lang-nursery/lazy-static.rs |
| linked_list_allocator | runtime    | Apache-2.0/MIT    | https://github.com/phil-opp/linked-list-allocator   |
| …

doc: Add external dependenices of RMM & SDK

---

.github/workflows/ci.yml
.gitmodules
scripts/config.py
scripts/fvp-cca
scripts/init_min_tf_a_rss.sh

ACS uses uart2 for reporting. TF-A-RSS(TF-A patched for RSS) also seems to use uart2.
So. it's hard to use unified tf-a without modifying.
To move forward, I think it's better to keep both tf-a & tf-a-rss before resolving the issue.
`--hes` option is needed.
```sh
./scripts/fvp-cca -nw=tf-a-tests -rmm=tf-rmm --hes 
```

Keep both tf-a and tf-a-rss

---

rmm/src/realm/mm/stage2_tte.rs
scripts/tests/acs.sh

This PR is a minor fix in s2tte's checking logic. With the fix, the remaining test in ACS's rtt_read_entry will be passed.
[before]
```
TOTAL TESTS     : 59
TOTAL PASSED    : 11
TOTAL FAILED    : 41
```
[after]
```
TOTAL TESTS     : 59
TOTAL PASSED    : 12
TOTAL FAILED    : 40
```

Fix a missing case in s2tte's is_assigned check

---

rmm/src/realm/mm/stage2_translation.rs

Stage 2 table should be drop by RTT_DESTROY

rmm: Do not drop the stage 2 table as RAII

---

lib/armv9a/src/regs.rs
rmm/src/exception/trap.rs

This PR injects undefined exception into the realm according to spec.
_This PR requires https://github.com/Samsung/islet/pull/197 to launch realms properly._
- exception_rec_exit_hvc
```sh
***** RMM ACS Version 0.7 *****
Suite=exception : exception_rec_exit_hvc
...
esr_el1  2000000
REALM handled the SEA(For HVC) successfully
Result => Passed
```
- spec: A4.3.4 REC exit due to synchronous exception

rmm: Inject undefined exception into the realm on HVC

---

rmm/src/event/rsihandle.rs
rmm/src/exception/trap.rs
rmm/src/realm/registry.rs
rmm/src/rmi/mod.rs
rmm/src/rmi/realm/rd.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rmi/rec/run.rs
rmm/src/rsi/hostcall.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/psci.rs
scripts/tests/acs.sh

This PR is related with #188 issue.
With this PR, we can see the realm is boot successfully in ACS test.

Patch for the setup of realm in ACS

---

rmm/src/granule/mod.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/registry.rs
rmm/src/rmi/realm/params.rs
rmm/src/rmi/rtt.rs
scripts/tests/acs.sh

This PR adds missing checks and cases in rtt_create and rtt_init_ripas. All the remaining tests regarding these APIs will be passed.
[before]
```
TOTAL TESTS     : 59
TOTAL PASSED    : 16
TOTAL FAILED    : 40
```
[after]
```
TOTAL TESTS     : 59
TOTAL PASSED    : 17
TOTAL FAILED    : 28
```
rtt_init_ripas now fail after rebasing. I will fix this issue in another PR.

Pass the remaining tests in rtt_init_ripas and rtt_create

---

rmm/Cargo.toml
rmm/src/host/mod.rs
rmm/src/lib.rs
rmm/src/measurement/ctx.rs
rmm/src/measurement/error.rs
rmm/src/measurement/hash.rs
rmm/src/measurement/mod.rs
rmm/src/realm/mod.rs
rmm/src/realm/registry.rs
rmm/src/rmi/error.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/realm/params.rs
rmm/src/rmi/realm/rd.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rmi/rec/params.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/error.rs
rmm/src/rsi/mod.rs

This PR add the ability to take and read measurements of realms. To accomplish this, I added appropriate fields inside the Realm and rd objects and modified several RMI handler to measure the passed parameters. Additionally, I add 2 missing RSI call allowing for reading and extending the measurements, basically reading RIM and extending REMs. This yields measurements that are binary compatible with beta0 version of tf-rmm provided in islet-assets repo.

Add measurements

---

rmm/src/host/pointer.rs
rmm/src/rmi/error.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rmi/rec/run.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/psci.rs

This PR passes whole REALM_REC_ENTER cases.
- Handle `RSI: PCSI_SYSTEM_OFF`
- Add runnable field to REC and error codes
```sh
***** RMM ACS Version 0.7 *****
Suite=command : cmd_rec_enter
HOST :
Check 1 : run_align; intent id : 0x0
rec: 0x88309000, run_ptr 0x8833F001
Check 2 : run_bound; intent id : 0x1
rec: 0x88309000, run_ptr 0x1C0B0000
Check 3 : run_bound; intent id : 0x2
rec: 0x88309000, run_ptr 0x1000000001000
Check 4 : run_pas; intent id : 0x3
rec: 0x88309000, run_ptr 0x88342000
Check 5 : run_pas; intent id : 0x4
rec: 0x88309000, run_ptr 0x6000000
Check 6 : rec_align; intent id : 0x5
rec: 0x88309001, run_ptr 0x8833F000
Check 7 : rec_bound; intent id : 0x6
rec: 0x1C0B0000, run_ptr 0x8833F000
Check 8 : rec_bound; intent id : 0x7
rec: 0x1000000001000, run_ptr 0x8833F000
Check 9 : …
```

acs: Pass REALM_REC_ENTER cases

---

rmm/src/measurement/ctx.rs
rmm/src/measurement/hash.rs
rmm/src/rsi/mod.rs

I fixed some silly mistakes. Now the extended measurements are identical to those from tf-rmm and the argument validation code should return correct error codes.

Fix REM extend and error handling

---

rmm/src/event/rsihandle.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/registry.rs
rmm/src/rmi/mod.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rmi/rec/run.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/constraint.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/psci.rs

Some ACS testcases are failed because the islet don't have RSI::IPA_STATE_GET command.
This PR makes it pass on below testcases :
```bash
cmd_ipa_state_get
mm_ripas_change
mm_ripas_change_reject
mm_ripas_change_partial
```

Add RSI::IPA_STATE_GET command

---

rmm/src/event/mod.rs
rmm/src/granule/mod.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/mod.rs
scripts/tests/acs.sh

Add some failure conditions on RSI_REALM_CONFIG, RSI_IPA_STATE_SET
It can pass the below test cases:
```bash
Suite=command : cmd_realm_config
REALM : 
Check 1 : addr_align; intent id : 0x0 
Check 2 : addr_bound; intent id : 0x1 
Result => Passed
Suite=command : cmd_ipa_state_set
REALM : 
Check 1 : addr_align; intent id : 0x0 
Check 2 : size_bound; intent id : 0x1 
Check 3 : rgn_bound; intent id : 0x2 
Check 4 : ripas_valid; intent id : 0x3 
Result => Passed
```

Add rsi failure contions

---

rmm/src/rmi/rtt.rs
scripts/tests/tf-a-tests.sh

This PR adds missing checks in data_create_unknown. All the remaining tests in ACS's data_create_unknown will be passed after this change. It also includes the commit resolving [the ci storage issue](https://github.com/Samsung/islet/issues/136). 
[before]
```
TOTAL TESTS     : 51
TOTAL PASSED    : 28
TOTAL SIM ERROR : 2
```
[after]
```
TOTAL TESTS     : 51
TOTAL PASSED    : 29
TOTAL SIM ERROR : 1
```

Pass the remaining tests in data_create_unknown

---

.gitmodules

This PR adds the kvmtool-rim-measurer tool for calculating Realm Initial Measurement.

Add the third-party/kvmtool-rim-measurer submodule

---

scripts/deps/submodule.sh

This PR partly addresses https://github.com/Samsung/islet/issues/218 by maintaining only the last git commit in the third-party submodules. The consumption would be reduced to around 21GB from around 83GB.
[before]
```
$ du -sh .git/modules/third-party/*
4.9G    .git/modules/third-party/android-kernel
4.9G    .git/modules/third-party/cca-rmm-acs
4.9G    .git/modules/third-party/gki-build
4.9G    .git/modules/third-party/kvmtool
4.9G    .git/modules/third-party/kvmtool-rim-measurer
4.9G    .git/modules/third-party/kvm-unit-tests
4.9G    .git/modules/third-party/mbedtls
4.9G    .git/modules/third-party/nw-linux
4.9G    .git/modules/third-party/optee-build
4.9G    .git/modules/third-party/realm-linux
4.9G    .git/modules/third-party/tf-a
4.9G    .git/modules/third-party/tf-a-rss
4.9G …
```

script: Remove git log in submodules to save disk space

---

rmm/src/realm/mm/page_table/pte.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/rmi/rtt.rs
scripts/fvp-cca

This PR adds missing checks in rtt_map_unprotected. All the tests in ACS's rtt_map_unprotected will be passed after this change. 
[before]
```
TOTAL TESTS     : 51
TOTAL PASSED    : 29
TOTAL FAILED    : 19
```
[after]
```
TOTAL TESTS     : 51
TOTAL PASSED    : 30
TOTAL FAILED    : 18
```

Add validity checks in rtt_map_unprotected

---

lib/armv9a/src/regs.rs
rmm/src/event/realmexit.rs
rmm/src/exception/trap.rs
rmm/src/granule/mod.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/registry.rs
rmm/src/rmi/mod.rs
rmm/src/rmi/rec/handlers.rs

It handles an exception for a data abort from the realmexit
according to 'A4.3.4.3 REC exit due to Data Abort'.
it constructs 'Exit' fields differently especially
for the 'exit.esr' register based by the below two types of data abort:
1. Emulatable Data Abort
2. Non-Emulatable Data Abort
It can pass below testcases :
```bash
exception_emulatable_da
exception_non_emulatable_da_1
exception_non_emulatable_da_2
mm_hipas_destroyed_ripas_ram_da
mm_protected_ipa_boundary
TOTAL TESTS     : 51
TOTAL PASSED    : 35
```

Handle realm exit data abort

---

rmm/src/event/realmexit.rs
rmm/src/event/rsihandle.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/psci.rs

It's related #222 issue and it's from #223 because a push permission was changed..
This PR add immutable Rd fields (realmid, ipa_bits) to Rec struct.
Multiple RECs can be created per Realm.
So the mentioned fields of rec are always valid before destroying the current Rec

Add immutable rd fields to Rec

---

scripts/fvp-cca
scripts/tests/realm-boot.sh

This PR enables `realm_linux` feature to rmm automatically when the realm is the linux.
```sh
./scripts/fvp-cca -nw=linux -rm=linux --realm-linux
```
```sh
./scripts/fvp-cca -nw=linux -rm=linux
```

scripts: Apply realm_linux feature to rmm naturally

---

.github/workflows/ci.yml
rmm/Cargo.toml
rmm/src/granule/translation.rs
sdk/Cargo.toml
sdk/Makefile
sdk/examples/simulated.rs
sdk/src/lib.rs
sdk/src/sealing.rs

This PR is for resolving the following error in ci.
```
Run actions-rs/audit-check@v1
/home/runner/.cargo/bin/cargo generate-lockfile
Updating crates.io index
Calling cargo-audit (JSON output)
Warning: 1 vulnerabilities found!
Warning: 1 warnings found!
Found 1 advisory(ies), 1 other
Warning: Unknown warning kind unsound found, please, file a bug
Error: Critical vulnerabilities were found, marking check as failed
```
[The vulnerability](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-49092) has been reported to be inside rsa module.
```
$ cargo audit
Crate:     rsa
Version:   0.9.2
Title:     Marvin Attack: potential key recovery through timing sidechannels
Date:      2023-11-22
ID:        RUSTSEC-2023-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0071
Solution:  No …
```

Use openssl crate to avoid a vulnerability in rsa crate

---

scripts/deps/pkgs.sh
scripts/fvp-cca

This PR fixes to run `linux-net` on WSL.
```sh
make[1]: Entering directory '/home/sangwan/islet/third-party/realm-linux'
/bin/sh: 1: bc: not found
=> apt install bc
```
```sh
OSError: [Errno 6] No such device or address
=> user_name = os.environ['USER']  
```

Fix to run linux-net on WSL

---

sdk/examples/aarch64.rs
sdk/examples/simulated.rs
sdk/src/lib.rs
sdk/src/sealing.rs

I found this issue while running the `certifier` example.
When a certifier's app calls unseal(), the return value should be fit the decrypted size without the plaintext's size.

sdk: Fit return's size of un/seal() properly

---

rmm/src/measurement/ctx.rs
rmm/src/realm/registry.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/attestation/mod.rs
rmm/src/rsi/measurement.rs
rmm/src/rsi/mod.rs

This PR contains the refactoring commit related to the earlier discussion (#231) and PR (#235). Previously, RSI interface trait was mainly used to sidestep the dependency issue between monitor and armv9a. Now that the dependency issue has been resolved by the integration (#175), the trait itslef doesn't have to be maintained.
[before]
```
rmm/src/realm/registry.rs contained the detailed RSI implementation with trait.
```
[after]
```
The below contains each module's corresponding RSI implementation without trait.
{
rmm/src/rsi/measurement.rs      { (measurement_)read, 
(measurement_)extend }
rmm/src/rsi/attestation/mod.rs  { get_(attestation_)token }
}
Note that the names inside the parentheses were removed to avoid duplicate words in namespace 
(e.g., measurement::measurement_read => …
```

Remove rsi::Interface trait

---

rmm/src/realm/mm/stage2_tte.rs
rmm/src/rmi/rec/mpidr.rs

This PR is a prerequisite for KLEE integration. Before this change, KLEE has aborted on compiling the previous code.
Relates to one of the cases in #247

klee: Fix self's usage where its reference is implied

---

.gitmodules

This PR bumps submodule's url from `Samsung/islet-assets` to `islet-project/assets`.

Fix submodule's url to islet-project

---

README.md
doc/components/attestation.md
doc/components/index.md
doc/crates/index.md
doc/getting-started/app-dev.md
doc/getting-started/index.md
doc/platform-development/index.md
doc/usecases/index.md

Note : There was typo on [1](https://github.com/islet-project/islet/compare/doc-new-org?expand=1#diff-622c19b11ccbda258b9458bbeb8aeb35fe20311bfd6c32ffe8a24bda625d52cdL4) and [2](https://github.com/islet-project/islet/compare/doc-new-org?expand=1#diff-622c19b11ccbda258b9458bbeb8aeb35fe20311bfd6c32ffe8a24bda625d52cdL7). Please let me know if this is intended

doc: Apply new org url

---

doc/SUMMARY.md
doc/usecases/cross-platform-e2ee.md
doc/usecases/index.md
examples/cross-platform-e2ee/README.md
scripts/make_doc.sh

This PR adds `Remote Attestation` to our dev-site.
Please refer [this](https://islet-project.github.io/islet/usecases/remote-attestation.html).
(_Our dev-site is latest version include https://github.com/islet-project/islet/pull/266_).

doc: Add `Remote Attestation` to dev-site

---

lib/vmsa/src/lib.rs
lib/vmsa/src/page_table.rs
rmm/src/realm/mm/stage2_translation.rs

This PR is based by the following requests:
1. Subtable's entry size don't need to be fixed by the first page table entry size 'N'
2. A new trait for memory alloc/dealloc is needed for PageTable structure for allowing to have different memory management methods per PageTable. (especially for stage2 page table)

vmsa: Add MemAlloc trait for PageTable

---

.cargo/config
plat/fvp/.cargo/config

This PR would resolve the below issue in CI, which was caused by `half` crate's version update.
```
(in plat/fvp)
$ cargo build
...
error: register class `vreg` requires the `neon` target feature
--> /home/changho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.3.1/src/binary16/arch/aarch64.rs:171:9
|
171 |         in(vreg) a,
|         ^^^^^^^^^^
error: register class `vreg` requires the `neon` target feature
--> /home/changho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.3.1/src/binary16/arch/aarch64.rs:172:9
|
172 |         in(vreg) b,
|         ^^^^^^^^^^
error: could not compile `half` (lib) due to 32 previous errors
```

 Add neon in target-feature to resolve a dependency issue

---

.github/workflows/ci.yml
.gitmodules
scripts/analyze-unsafe.sh
scripts/init-unsafe-analysis.sh

This PR introduces `cargo gegier` to analysis `unsafe ratio`.
You can check this on [CI](https://github.com/islet-project/islet/actions/runs/7605666158/job/20710259988).
```sh
Functions  Expressions  Impls  Traits  Methods  Dependency
1/6=16.67%     8/42=19.05%        0/0=100.00%        0/0=100.00%     0/0=100.00%  !  fvp 0.0.1
2/2=100.00%    16/18=88.89%        1/1=100.00%        0/0=100.00%     1/1=100.00%  !  ├── armv9a 0.0.1
20/20=100.00%    75/75=100.00%      15/15=100.00%       0/0=100.00%    15/15=100.00%  ?  ├── bitflags 1.3.2
116/126=92.06%  3776/4746=79.56%    134/136=98.53%       7/7=100.00%   269/297=90.57%  !  ├── islet_rmm 0.0.1
...
1687/1740=96.95% 122331/126205=96.93%  5926/6029=98.29%    353/375=94.13%  8456/8562=98.76%
```

tools: Add unsafe analyzer `cargo gegier`

---

.gitmodules
scripts/fvp-cca

This PR moves tf-a from `assets's branch` to the [forked repo](https://github.com/islet-project/arm-trusted-firmware).
- upstream: master branch
- rss parched: rss branch
I will remove `3rd-tf-a` and `3rd-tf-a-rss` branches on `assets repo` after this PR merged.

third-party: tf-a: Fix to use the forked url

---

rmm/src/config.rs
rmm/src/exception/trap.rs
rmm/src/mm/translation.rs
rmm/src/rmm_el3/mod.rs

This PR adds the shared memory mapping of rmm_el3, which was not registered in RMM's page table. With the fix, the unnecessary fault related to that address would not be generated.
```
[before]
[TRACE]islet_rmm::rmm_el3 -- Setup EL3 interface
[DEBUG]islet_rmm::exception::trap::syndrome -- Data Abort without a change in Exception level
[DEBUG]islet_rmm::exception::trap -- Data Abort (higher), far:FFBFF000
[DEBUG]islet_rmm::exception::trap -- translation, level:2, esr:96000146
[TRACE]islet_rmm::rmm_el3::iface -- GET_REALM_ATTEST_KEY
[after]
[TRACE]islet_rmm::rmm_el3 -- Setup EL3 interface
[TRACE]islet_rmm::rmm_el3::iface -- GET_REALM_ATTEST_KEY
```

Add the shared memory mapping of rmm_el3

---

doc/getting-started/plat-dev.md
plat/fvp/src/entry.rs
rmm/src/granule/array/entry.rs
rmm/src/granule/array/mod.rs
rmm/src/lib.rs
scripts/tests/acs.sh

This PR refactors granule status table's initialization code to use `lazy_static` macro, so that the accesses to it would not involve unsafe operations. As a result, 3 unsafe blocks have been removed. Also, some build errors of using the latest rustc (24-03-01) have been resolved.
```
(Unsafe-analysis results from cargo-geiger)
x = safe code found in the crate
y = total code found in the crate
z = percentage of safe ratio as defined by x/y
Functions         Expressions       Module
[before]
122/132=92.42%  3814/4802=79.43%    islet_rmm 0.0.1
[after]
121/131=92.37%  3811/4793=79.51%    islet_rmm 0.0.1
```

Use lazy_static for granule status table

---

examples/cross-platform-e2ee/setup.sh

This commit fixes the following error while executing e2ee example's setup.sh script.
```
(in examples/cross-platform-e2ee)
$ setup.sh
...
make[1]: Leaving directory '/islet/examples/cross-platform-e2ee/protobuf'
Cloning into 'gflags'...
remote: Enumerating objects: 2458, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 2458 (delta 32), reused 57 (delta 29), pack-reused 2387
Receiving objects: 100% (2458/2458), 1.53 MiB | 2.18 MiB/s, done.
Resolving deltas: 100% (1434/1434), done.
CMake Warning:
No source or binary directory provided.  Both will be assumed to be the
same as the current working directory, but note that this warning will
become a fatal error in future CMake releases.
-- The CXX compiler identification is …
```

Fix a build error of e2ee setup script

---

lib/rsi-el0/src/lib.rs

This commit modifies the measurement length returned from linux-rsi module. RMM returns a zero-padded measurement value and linux-rsi module currently returns the maximum measurement length. Modifying the measurment length is necessary in order not to display the zero-padding in cli. The displayed format becomes consistent with the cross-platform-e2ee example's README.
```
(in realm's shell)
[before]
$ ./islet measurement-read --index 0
[  208.236303] rsi: device rsi open
[  208.269598] rsi: ioctl: measurement_read: 0
[  208.306435] rsi: device rsi released
"be33b6c8bf03e85fec35fdd3a3b856adbc61b525e901e59d701ca33a8c71408c0000000000000000000000000000000000000000000000000000000000000000"
[after]
$ ./islet measurement-read --index 0
[  206.805345] rsi: device rsi open
[  206.838067] rsi: …
```

rsi-el0: Remove the zero-padding in the display

---

lib/autopadding/Cargo.toml
lib/autopadding/src/lib.rs
rmm/Cargo.toml
rmm/src/rmi/realm/params.rs
scripts/clippy.sh

- Introduce auto-padding macro, with automatic impl for `Default` trait as well.
- Wrap with `pad_struct_and_impl_default` macro on type definition.
- Supports only integer primitives and arrays of it. In case of new type field is needed(which I believe there is no use of it though), you need to add type initialization matching on `type_check_and_init` macro. For instance, to introduce `f32`, add 
~~~
(f32) => {
0.0
};
~~~
- Last arm of `type_check_and_init` matches with array type.
- Any naming suggestion is welcomed

Add auto-padding macro 

---

.cargo/config
.github/workflows/ci.yml
.gitmodules
cli/Cargo.toml
hes/islet-hes-host-app/Cargo.toml
hes/islet-hes/Cargo.toml
lib/cca-token/Cargo.toml
lib/cose/Cargo.toml
plat/fvp/.cargo/config
rmm/Cargo.toml
scripts/deps/assets.sh
scripts/init_min.sh
scripts/init_min_acs.sh
scripts/init_min_tf_a.sh
scripts/init_min_tf_a_rss.sh

This PR reverts #270, as neon target-feature has a side-effect of using additional registers for context switch (found by @bokdeuk-jeong). `ciborium` and `coset` crate, which are being used by attestation, have been added as git submodules and locally-linked in `Cargo.toml` to constrain `half` crate's version to the one which does not cause a build error related to neon target-feature.
Note that `git submodule update --init --depth 1 --recursive` should be executed once for the existing islet repository to build islet RMM successfully.
[before]
```
$ cargo tree
...
├── islet_rmm v0.0.1 (/home/changho/zpzigi754/islet/rmm)
│   ├── armv9a v0.0.1 (/home/changho/zpzigi754/islet/lib/armv9a)
│   ├── ciborium v0.2.2
│   │   ├── ciborium-io v0.2.2
│   │   ├── ciborium-ll v0.2.2
│   │   │   ├── …
```

Do not use neon target-feature

---

scripts/config.py
scripts/fvp-cca

This PR revives `--trace` option in fvp-cca and makes it available in all normal world instances including acs-tests, tf-a-tests, linux-net, and aosp. `--debug` and `--no-telnet` options also get refactored for consistency. 
```
Usage)
$ ./scripts/fvp-cca -nw=acs --trace
$ head out/trace.log
200000000000 ps cluster0.cpu0 IT (20000000) fdc3b1c0 8a2801ef O EL2h_rl : BIC      x15,x15,x8
200000000000 ps cluster0.cpu0 R X15 0000000000000000
200000010000 ps cluster0.cpu0 IT (20000001) fdc3b1c4 aa0e01ee O EL2h_rl : ORR      x14,x15,x14
200000010000 ps cluster0.cpu0 R X14 2625AA4DCF2A5456
200000020000 ps cluster0.cpu0 IT (20000002) fdc3b1c8 8a0d010d O EL2h_rl : AND      x13,x8,x13
200000020000 ps cluster0.cpu0 R X13 BED0458D797DFE83
200000030000 ps cluster0.cpu0 IT (20000003) fdc3b1cc 8a28020f O …
```

Allow trace and debug options for all normal world

---

scripts/config.py
scripts/deps/simulator.sh
scripts/fvp-cca

This commit adds `--trace-toggle` option for `ToggleMTIPlugin` which enables toggling the behavior of instruction tracing. The plugin would be useful for the target-specific performance evaluation as well as debugging. The toggling is controlled by pre-reserved `hlt 5` instruction.
Note that the simluator should be updated to the latest one using `./scripts/deps/simulator.sh` for the compatibility with the used library. Also, the library (ToggleMTIPlugin.so) is not included in the simulator package. It should be manually located by installing another package such as `FastModelsPortfolio_11.25` which requires license agreement.
```
(in linux/arch/arm64/kernel/head.S)
SYM_CODE_START(primary_entry)
+	hlt	5				// trace start 
bl	preserve_boot_args 
bl	init_kernel_el 
mov	x20, x0
+	hlt	5				// …
```

fvp-cca: Add instruction trace toggling

---

rmm/Cargo.toml
rmm/src/realm/config.rs
rmm/src/rsi/hostcall.rs
rmm/src/rsi/mod.rs

This PR fixes structures, passed from realm, to use safe abstraction.
- Removed 3 unsafe methods & 2 unsafe code blocks
_(Followed PR: [Draft safe-abstraction library to enhance safety of raw pointers](https://github.com/islet-project/islet/pull/298))_
- RsiHostCall: Manaully Reviewed
- RsiRealmConfig: Manaully Reviewed

Fix structures, passed from realm, to use safe abstraction

---

rmm/src/rmi/features.rs

This PR fixes one correctness bug, found by [model checking](https://en.wikipedia.org/wiki/Model_checking) ([relevant PR](https://github.com/islet-project/islet/pull/234)). It also explicitly assigns a value of zero to X1 for better understanding of RMI features' behavior.
[B3.3.4.2 in beta0 and B4.3.4.2 in eac5]
```
The RMI_FEATURES command does not have any failure conditions.
```
[B3.3.4.3 in beta0 and B4.3.4.3 in eac5]
```
pre: index != 0
post: X1 == Zero()
```

Fix return values in rmi features

---

scripts/pylint.sh
scripts/unsafe-analyzer

This PR prints the accurate count of unsafe keywords with `unsafe-analyzer`.
- Cargo-geiger cannot analyze macros, hence the number is approximate.
- Ref: [The unsafe keyword](https://doc.rust-lang.org/reference/unsafe-keyword.html#the-unsafe-keyword)
```sh
$ ./scripts/unsafe-analyzer
Unsafe Keywords:
- Total           | 199
- Functions       | 35
- Blocks          | 161
- Impls           | 3
Unsafe Usage(approximate figures):
- Total           | 163
- Deref Operation | 23
- Unclassified    | 137
- Skipped         | 3
Unsafe Internal(approximate figures):
- Exprs           | 407
- Stmts           | 234
```

scripts: Print the accurate count of unsafe keywords

---

rmm/src/rmi/constraint.rs
rmm/src/rsi/constraint.rs

This PR refactors constraint retrieval procedure of RMI and RSI. The main motivation of the refactoring is that insertion & get in the map are very expensive operations especially in the formal semantic and avoiding them is better if possible. It would be also beneficial for runtime performance, as the previous insertions are no longer involved. The change assumes that the configuration regarding constraints does not change at runtime.
[before]
```
lazy_static! {
static ref CONSTRAINTS: BTreeMap<Command, Constraint> = {
let mut m = BTreeMap::new();
m.insert(rmi::VERSION, Constraint::new(rmi::VERSION, 1, 1));
...
(caller)
if let Some(c) = CONSTRAINTS.get(&cmd) {
```
[after]
```
fn pick(cmd: Command) -> Option<Constraint> {
let constraint = match cmd {
rmi::VERSION => …
```

Refactor constraint retrieval procedure

---

scripts/unsafe-analyzer

This PR temporarily fixes the below ci issue related to `Run unsafe analyzer` workflow. The keyword which the script is looking for seems to be missing for some reason.
```
Run ./scripts/unsafe-analyzer
...
[!] Running cargo geiger...
[!] Failed to run: cargo geiger --output-format Ratio @ /root/islet/plat/fvp
Failed to match (ignoring source) package: libc 0.2.153 (registry+https://github.com/rust-lang/crates.io-index)
Failed to match (ignoring source) package: libc 0.2.153 (registry+https://github.com/rust-lang/crates.io-index)
Failed to match (ignoring source) package: libc 0.2.153 (registry+https://github.com/rust-lang/crates.io-index)
...
```

ci: Do not exit failure even if a keyword is not found

---

scripts/deps/cross.sh

This PR resolves the `serde` compatibility issue.
```
Compiling serde v1.0.198
error[E0658]: use of unstable library feature 'saturating_int_impl'
--> /home/sangwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.198/src/lib.rs:279:13
|
279 |     pub use self::core::num::Saturating;
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #87920 <https://github.com/rust-lang/rust/issues/87920> for more information
= help: add `#![feature(saturating_int_impl)]` to the crate attributes t
```

3rd: Pin serde version to fix the build-error 

---

.github/workflows/ci.yml

This PR applies `cargo-vet` to CI
ref) https://mozilla.github.io/cargo-vet/

ci: Add cargo vet to ensure that 3rd-party deps

---

.github/workflows/ci.yml

This PR applies caching for the `assets` directory within our github action workflow.
This change results about 5 minutes reduction when it takes to download the entire assets.

ci: Cache assets

---

scripts/deps/pkgs.sh

This PR fixes [the CI error](https://github.com/islet-project/islet/actions/runs/8776046268/job/24079464476).
- Apply `sudo apt update` with `--fix-missing` which addressed issues caused by missing packages sources
- Fix to use `apt-get` which provides a stable CLI interface for automated environments

ci: Fix the error related with installing packages

---

rmm/src/granule/array/entry.rs

This PR fixes a bug in `granule_undelegate`, found by model checking. Note that the previous page table-based GST didn't contain this bug.
[B.3.3.6.3 Success conditions in beta0 (B.4.3.6.3 in eac5)]
```
ID                 Condition
...
gran_content       Contents of target Granule are wiped.
```

Do not miss content wiping in granule undelegate

---

rmm/src/rmi/realm/mod.rs

This PR fixes page table mapping related to RTT base. Note that `rtt_num_start` indicates the number of physically contiguous starting level RTTs. The patch connects the correct number of RTTs in the page table during realm creation. As a result, the unnecessary faults related to those addresses would not be generated in realm-linux booting.
```
[before]
...
[TRACE]islet_rmm::event -- RMI: REC_AUX_COUNT        [882E99000] > [0, 10]
[DEBUG]islet_rmm::exception::trap::syndrome -- Data Abort without a change in Exception level
[DEBUG]islet_rmm::exception::trap -- Data Abort (higher), far:881BC2000
[DEBUG]islet_rmm::exception::trap -- translation, level:3, esr:96000007
[TRACE]islet_rmm::event -- RMI: RTT_INIT_RIPAS       [882E99000, 80000000, 3] > [204, 0]
...
[TRACE]islet_rmm::event -- RMI: …
```

Fix data aborts related to RTT base

---

lib/safe-abstraction/src/lib.rs
rmm/src/host/mod.rs
rmm/src/realm/config.rs
rmm/src/rmi/error.rs
rmm/src/rsi/mod.rs

This PR adds `Error` to `safe-abstraction`. 
- Reflected [review](https://github.com/islet-project/islet/pull/290#discussion_r1552693060)
- Followed PR: [Fix structures, passed from host, to use safe abstraction](https://github.com/islet-project/islet/pull/297)

safe-abstraction: Add Error Code

---

rmm/src/event/rsihandle.rs
rmm/src/exception/lower/synchronous/sys_reg.rs
rmm/src/exception/trap.rs
rmm/src/gic.rs
rmm/src/measurement/ctx.rs
rmm/src/mmio.rs
rmm/src/realm/config.rs
rmm/src/realm/context.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/mod.rs
rmm/src/realm/registry.rs
rmm/src/realm/timer.rs
rmm/src/realm/vcpu.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/realm/rd.rs
rmm/src/rmi/rec/exit.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/mod.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/measurement.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/psci.rs
rmm/src/rtt.rs

This PR contains the refactoring commits related to the earlier discussion (#230). Realm and Rd (Realm Descriptor) have almost the same purpose. It aims to keep only Rd which is defined by spec.
```
-pub struct Realm {
-   id: usize,
-   pub vmid: u16,
-   pub state: State,
-   pub vcpus: Vec<Arc<Mutex<VCPU>>>,
-   pub page_table: Arc<Mutex<Box<dyn IPATranslation>>>,
-   pub measurements: [Measurement; MEASUREMENTS_SLOT_NR],
-}
pub struct Rd {
-   realm_id: usize,
+   vmid: u16,
...
+   s2_table: Arc<Mutex<Box<dyn IPATranslation>>>,
hash_algo: u8,
+   pub measurements: [Measurement; MEASUREMENTS_SLOT_NR],
+   pub vcpus: Vec<Arc<Mutex<VCPU>>>,
}
```
- `vmid` is integrated with `id` so that only `vmid`, passed by the Host, is used
- `VMID_SET` is used instead of the previous `RMS` (Realm …

Integrate realm and rd

---

rmm/src/event/mod.rs
scripts/clippy.sh

Minor fix for denying warnings

Apply `--deny warnings` to clippy

---

rmm/src/stat.rs

Because `COLLECTED_STAT_CNT` is already used after holding a lock in STATS, 
it doesn't need to be global. So it's better to includes it into Stats structure
This PR can resolve #314.

stat: Include COLLECTED_STAT_CNT into Stats

---

.github/workflows/ci.yml
.gitmodules
scripts/tests/certifier-compatibility.sh

This PR enables the `Certifier` job.
- Checks whether the latest `Islet SDK` and `Certifier` are compatible.
- Cross-test related with this PR: https://github.com/ccc-certifier-framework/certifier-framework-for-confidential-computing/pull/245

ci: Add certifier compatibility test

---

README.md
doc/SUMMARY.md
doc/getting-started/index.md
doc/getting-started/verification.md
model-checking/Cargo.toml
model-checking/Makefile
model-checking/src/common.rs
model-checking/src/lib.rs
model-checking/src/rmi_granule_delegate.rs
model-checking/src/rmi_granule_undelegate.rs
model-checking/src/stub.c
rmm/Cargo.toml
rmm/src/asm.rs
rmm/src/event/mainloop.rs
rmm/src/event/mod.rs
rmm/src/granule/array/entry.rs
rmm/src/granule/array/mod.rs
rmm/src/rmi/gpt.rs

This PR adds two verification harnesses for model checking: RMI_GRANULE_DELEGATE and RMI_GRANULE_UNDELEGATE.
It found one correctness bug (https://github.com/islet-project/islet/pull/307). 
```
(in islet/model-checking)
$ RMI_TARGET=rmi_granule_(un)delegate make verify 
...
SUMMARY:
** 0 of 3055 failed (81 unreachable)
** 14 of 14 cover properties satisfied
```
- Add a ghost gpt field in granule entry for tracking Granule Protection Table (GPT)'s change
- Add `is_valid` predicate for ensuring Granule Status Table (GST)'s valid status
- Put common helper functions in `common` module (`pre_/post_granule_state()`, `pre_/post_granule_gpt()`, etc)
- Add host memory and EL3 gpt change modeling code to help harnesses interact with their environment
This models the Host memory as a pre-allocated …

Add harnesses for verifying rmi granule delegate and undelegate

---

scripts/deps/assets.sh

This is a minor PR for speeding up ci tests as well as reducing overall disk consumption. 
```
(in scripts/deps/assets.sh)
[before]
cd $ROOT && git submodule update --init assets
[after]
cd $ROOT && git submodule update --init --depth 1 assets
```

ci: Use depth 1 when syncing assets for speeding up

---

scripts/deps/rust.sh

This fix is intended for resolving the below error in AnalysisHub.
```
$ ./scripts/deps/rust.sh
...
Compiling tempfile v3.10.1
Compiling serde_derive v1.0.201
error[E0658]: use of unstable library feature 'saturating_int_impl'
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.201/src/lib.rs:280:13
|
280 |     pub use self::core::num::Saturating;
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #87920 <https://github.com/rust-lang/rust/issues/87920> for more information
= help: add `#![feature(saturating_int_impl)]` to the crate attributes to enable
...
```

scripts: Remove cargo install to avoid a feature error

---

lib/armv9a/src/macro.rs
lib/vmsa/src/lib.rs

This is for addressing the remaining issues in AnalysisHub. AnalysisHub uses clippy with more restrictive option (e.g., `-W clippy::all`) and removing `#![deny(warnings)]` in `vmsa` crate is necessary in order not to make the analysis fail. Bogus safety doc comments in `armv9a` crate are also added for similar reason.

Avoid clippy errors in AnalysisHub

---

lib/armv9a/src/regs.rs
plat/fvp/.cargo/config.toml
rmm/.cargo/config.toml
rmm/src/realm/timer.rs

This PR enables `FEAT_ECV` to use CNTPOFF_EL2.
We couldn't use the `CNTPOFF_EL2` register because `FEAT_ECV` was not enabled.
So we used `S3_4_C14_C0_6` as a workaround. 
According to the Arm specification, FEAT_ECV must be enabled to use `CNTPOFF_EL2`, so in this PR, i've enabled `FEAT_ECV` used the correct register name.
This PR emits an warning like below. However, it is better to use the correct target-feature to ensure proper functionality.
```rust
$ cargo build
warning: unknown and unstable feature specified for `-Ctarget-feature`: `ecv`
|
= note: it is still passed through to the codegen backend, but use of this feature might be unsound and the behavior of this feature can change in the future
= help: consider filing a feature request
```
---
This register is present only when …

rmm: Enable FEAT_ECV to use CNTPOFF_EL2

---

scripts/deps/pkgs-for-ci.sh
scripts/deps/pkgs.sh
scripts/tests/acs.sh
scripts/tests/realm-boot.sh

This PR improves the ACS test and realm booting test.
- Using `inotifywait`, it terminates when a file is not changed for a specific amount of time.
- If the exit condition matches the last change, it exits immediately.
- The time required for `realm-booting job of CI` has been reduced by half. (about 15m -> 7m)

ci: Enhance tests with inotifywait

---

Cargo.lock
lib/vmsa/Cargo.toml
lib/vmsa/src/guard.rs
rmm/src/granule/array/entry.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/rd.rs
rmm/src/rec.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/rec/exit.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/psci.rs
rmm/src/rsi/ripas.rs
rmm/src/rtt.rs

This PR applies safe abstraction to structures managed with granule locks.
1. The affected structures are RD, RTT and REC.
2. `content_mut` has been modified to manage `&mut` in accordance with Rust's syntax.
3. Four `unsafe` keyword have been removed.

safe-abstraction: Apply to granule-locked structs

---

lib/armv9a/src/macro.rs
lib/armv9a/src/regs.rs
rmm/src/exception/trap/syndrome.rs

This PR removes all unsafe keywords related to system registers.
- The system registers that were used have been submitted upstream.
- https://github.com/rust-embedded/aarch64-cpu/pull/27

armv9a: Remove remaining sys register definitions

---

scripts/fvp-cca

This PR enables `--trace-toggle` option for ACS tests. The option allows specifying the range of instruction tracing with Arm's `ToggleMTIPlugin`, helping to debug a subtle symptom. For example, it helped me to analyze `rmi_rec_enter`, when it was not working. The instruction toggling is controlled by pre-reserved `hlt 5` instruction.
[Pre-requisite]
The library (ToggleMTIPlugin.so) is not included in our simulator package. It should be manually located by installing another package such as `FastModelsPortfolio_11.25` which requires license agreement.
[Usage example]
```
(in plat/fvp/src/entry.rs)
unsafe extern "C" fn rmm_entry() -> ! {
core::arch::asm!("
msr spsel, #1
bl get_cpu_id
+       hlt     5                   // trace start
ldr x1, =__RMM_STACK_END__
mov x2, {}
mul x0, x0, x2
sub …
```

fvp-cca: Support trace toggle in acs tests

---

.github/workflows/ci.yml
rmm/src/event/mainloop.rs
rmm/src/event/mod.rs
rmm/src/lib.rs
rmm/src/macro.rs
rmm/src/rmi/features.rs
rmm/src/rmi/version.rs
rmm/src/test_utils.rs
scripts/clippy.sh
scripts/init-unsafe-analysis.sh
scripts/tests/miri.sh

This PR sets up [MIRI](https://github.com/rust-lang/miri) to analyze potential memory safety violations arising from unsafe code at the MIR level.
`MIRI` is an interpreter that performs analysis at the MIR (Mid-level Intermediate Representation) level. Tests must be expressible in MIR to be testable with `MIRI`. Consequently, we are leveraging some test cases from the ACS project, originally written in C, by rewriting them in Rust.
To establish a Rust-based testing environment, I have added a `test_utils` module, allowing tests to be conducted at the function level rather than running the entire codebase. 
```rust
#[test]
fn rmi_features() {
let ret = rmi::<FEATURES>(&[0]);
assert_eq!(ret[0], SUCCESS);
...
}
#[test]
fn rmi_version() {
let ret = rmi::<VERSION>(&[encode_version()]); …
```

Setup MIRI Test

---

lib/vmsa/src/page_table.rs
rmm/src/granule/page_table/entry.rs
rmm/src/granule/page_table/mod.rs
rmm/src/granule/page_table/translation.rs
rmm/src/mm/page_table/entry.rs
rmm/src/mm/translation.rs
rmm/src/realm/mm/page_table/entry.rs
rmm/src/realm/mm/stage2_translation.rs

The ulimate goal is to eliminate redundant functions for the realm s2 table management which are scattered across the board in rtt.rs, stage2_translation.rs, stage2_tte.rs, page.rs and lib/vmsa.
Prior to that, this PR does followings.
1. Create a page table with an allocator that the function caller provides.
2. Return as a reference and reduce unsafe usages.
3. Simplify mutiple look-alike functions into one.

vmsa: introduce new_in() with an allocator as a parameter

---

examples/veraison/reliant-party/Cargo.toml
examples/veraison/reliant-party/src/main.rs

This change depends on https://github.com/islet-project/remote-attestation/pull/7, which simplifies the usage of realm-verification structures.
To verify either wait for merge or modify Cargo.toml entry for realm-verifier using path to local clone of repo instead of git address.

examples/reliant-party: Update to new realm-verifier

---

lib/armv9a/src/lib.rs
rmm/src/rsi/mod.rs

This reverts commit 2e0f9ffa672f526c91b5a6128cb70df082f33fd4.
It appears that some (maybe Islet) is not handling some IRQ properly. As a result this patch broke reading the attestation token even though the cca-rmm-acs tests were passing. It it most likely due to the fact that the test suite was a simple bare metal binary that doesn't utilize much of the emulated hardware. Reverting this patch doesn't remove any functionality. In the future, the IRQ handling should be investigated.

Revert "Use DUCT-TAPE to fix irq test"

---

lib/vmsa/src/page_table.rs
plat/fvp/.cargo/config.toml
rmm/.cargo/config.toml
rmm/src/granule/page_table/entry.rs
rmm/src/granule/page_table/translation.rs
rmm/src/mm/page.rs
rmm/src/mm/page_table/entry.rs
rmm/src/mm/translation.rs
rmm/src/realm/mm/entry.rs
rmm/src/realm/mm/mod.rs
rmm/src/realm/mm/page.rs
rmm/src/realm/mm/rtt.rs
rmm/src/realm/mm/stage2_translation.rs
rmm/src/realm/mm/stage2_tte.rs
rmm/src/realm/rd.rs
rmm/src/rmi/constraint.rs
rmm/src/rmi/mod.rs
rmm/src/rmi/rec/exit.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/ripas.rs

1. Implement RTT_FOLD RMI.    
- Added an RMI handler for RTT_FOLD.
- Provide an iterator for the entry enumeration in a table at a specific level in PageTable and use the iterator when rtt.rs needs to access the whole entries at a time like rtt-fold.
3. Fix errors in rtt found during the fold test.
- Fix errors in subtable access in PageTable
- Fix implementations that doesn't comply with RMM spec.
4. Tlb invalidation for state2 translation table
- added two versions of range invalidation, just for case that being unable to use tlb-rmi support.
5. Misc
- Move realm address space related checks which depends on ipa_bits to Rd.
- Remove is_raw() param of set() in Entry
```
REGRESSION REPORT:
==================
TOTAL TESTS     : 100
TOTAL PASSED    : 92
TOTAL FAILED    : 2
TOTAL SKIPPED   : …
```

    realm/mm: RMI_RTT_FOLD support

---

lib/safe-abstraction/src/lib.rs
lib/vmsa/src/guard.rs
rmm/src/granule/array/entry.rs
rmm/src/rec.rs
rmm/src/rmi/rec/handlers.rs

This PR presents a quick draft for safely creating an instance at a given memory address.
As discussed in https://github.com/islet-project/islet/pull/342, utilizing the idea proposed by @L0czek, this approach involves parsing the given address as uninitialized memory, then copying that instance to that address.
For REC and RD, the copy cost was not considered significant since the operation is called only once.
```rust
// Create Instance
let addr = GIVEN_ADDRESS;
let value = T;
unsafe {
let src: core::mem::MaybeUninit<T> = core::mem::MaybeUninit::new(value);
let src = &src as *const core::mem::MaybeUninit<T>;
let dst = addr as *mut core::mem::MaybeUninit<T>;
core::ptr::copy_nonoverlapping(src, dst, 1);
}
// Access Instance
let ptr = addr as *mut core::mem::MaybeUninit<T>;
let value = …
```

Safe instance creation at given memory address

---

rmm/src/realm/mm/rtt.rs
rmm/src/rmi/realm/mod.rs
scripts/tests/acs.sh

This fixes rtt_state in B4.3.9.2 and rtt_state in B4.3.9.3, found during the process of verification. The state should be checked and updated by the number of `rtt_num_start`. This PR also removes hundreds of annoying data aborts: I've handled it with a rather radical approach (mapping without unmapping), because using unmapping would affect too many interfaces. I will fix the below undestroyed issue and use the unmapping in another PR. 
```
B4.3.9.2 Failure conditions
rtt_state pre: !RttsStateEqual(
params.rtt_base, params.rtt_num_start, DELEGATED)
post: ResultEqual(result, RMI_ERROR_INPUT)
B4.3.9.3 Success conditions
rtt_state RttsStateEqual(
Realm(rd).rtt_base, Realm(rd).rtt_num_start, RTT)
```
```
[before]
[TRACE]islet_rmm::rmi::realm::params -- Params { flags: lpa2: 0 sve: 0 pmu: 0, …
```

Fix spec violations in realm create

---

doc/getting-started/plat-dev.md

Changed inmod rsi.ko to insmod rsi.ko in the doc/getting-started/plat-dev.md file.

Fix typo in documentation

---

rmm/src/realm/rd.rs
rmm/src/rmi/realm/mod.rs
scripts/tests/acs.sh

This PR fixes a spec violation regarding rtt_state in B4.3.10.3, found during the process of verification. As a result, it fixes the previous issue on ACS tests (mm_rtt_level_start and mm_ha_hd_access), described in #366.
The state should be updated by the number of `rtt_num_start`.
```
B4.3.10.3 Success conditions
rtt_state RttsStateEqual(
realm.rtt_base, realm.rtt_num_start, DELEGATED)
```

Fix a spec violation in realm destroy

---

rmm/src/asm.rs
rmm/src/granule/array/entry.rs
rmm/src/granule/array/mod.rs
rmm/src/lib.rs
rmm/src/mm/page_table/entry.rs
rmm/src/mm/translation.rs
rmm/src/realm/mm/entry.rs
rmm/src/realm/mm/stage2_translation.rs
rmm/src/rmi/gpt.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/realm/params.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rec/run.rs
rmm/src/rmi/rec/vtcr.rs
rmm/src/rmi/rtt.rs
rmm/src/test_utils.rs
scripts/tests/crates.sh
scripts/tests/miri.sh

This PR aims to introduce MIRI testing across all RMI functions to strengthen memory safety within RMM, particularly by addressing potential issues arising from `unsafe code`.
To cover all 23 RMI types, 11 new test cases (TCs) have been added (_see Appendix: MIRI Test Cases for details_), leading to the **discovery of 2 bugs** (1 memory leak, 1 integer overflow). Additionally, while writing the MIRI test cases, a manual review revealed a misalignment within the RMM specification, which was reported to Arm.
```sh
$ ./scripts/tests/miri.sh
running 22 tests
test r#macro::test::eprintln_with_format ... ok
test r#macro::test::eprintln_without_arg ... ok
test r#macro::test::eprintln_without_format ... ok
test r#macro::test::println_with_format ... ok
test r#macro::test::println_without_arg ... …
```

Cover all RMIs with MIRI testing

---

doc/dev-site.md

This PR updates the document about deployment (https://github.com/islet-project/islet/pull/261). `docs/` should be removed from `.gitignore` before making a commit, because otherwise the external links (e.g., plat-doc/islet_rmm) will be inaccessible after the deployment.

doc: Update the guide on deploying dev site

---

plat/fvp/src/main.rs
rmm/src/config.rs
rmm/src/lib.rs
rmm/src/mm/translation.rs

This PR moves platform-dependent values to the platform-specific crate.
As a first step, it moves values that are defined by `the platform's linker script`.
Additionally, the constant `FVP_DRAM_REGION`, which defines the DRAM region for FVP, will also be moved in a next PR. 
(_Since this will requires more complex changes include `get_granule_if!`, I plan to address this in a separate PR._)

Move platform-dependent values from rmm/ to plat/

---

scripts/configure_tap.sh

This PR fixes a simple mistake in configure_tap.sh. (i.e., using interface names given instead of the hard-coded one)
This issue caused the realm to not be able to connect to the host.

fix the hard-coded interface name

---

rmm/src/granule/array/entry.rs
rmm/src/rec.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/rec/handlers.rs

This adds a reference count and `num_children` support in array-based granule status table missing of which was the main cause for the previous ACS failures when gst_page_table feature was not enabled. Most of ACS tests will be passed with this fix.
```
[before]
REGRESSION REPORT:
==================
TOTAL TESTS     : 76
TOTAL PASSED    : 24
TOTAL FAILED    : 47
TOTAL SKIPPED   : 3
TOTAL SIM ERROR : 2
```
```
[after]
REGRESSION REPORT:
==================
TOTAL TESTS     : 76
TOTAL PASSED    : 71
TOTAL FAILED    : 1
TOTAL SKIPPED   : 3
TOTAL SIM ERROR : 1
```

Add a reference count in array-based granule status table

---

Cargo.lock
plat/fvp/Cargo.toml
rmm/Cargo.toml

The [PR](https://github.com/rust-embedded/aarch64-cpu/pull/27) merged and released at [v10.0.0](https://github.com/rust-embedded/aarch64-cpu/releases/tag/v10.0.0).
- The PR includes registers that we need
- I will remove the forked git, [islet-project/aarch64-cpu](https://github.com/islet-project/aarch64-cpu/), after this PR merged

aarch64-cpu: Bump to upstream v10.0.0

---

.github/workflows/ci.yml
.gitignore
scripts/code-coverage.sh
scripts/deps/rust.sh

This PR introduces the code coverage measurement .
Please refer the `code-coverage.sh` to run. Also you can check `code-coverage` files in the artifacts of [actions](https://github.com/islet-project/islet/actions).
```sh
./scripts/code-coverage.sh
firefox ./code-coverage/index.thml
```

ci: scripts: Add code coverage measurement

---

rmm/src/rmi/rtt.rs

The below feedback would be accepted in 1.1-alp10.
8466a917 spec: feedback: Ensuring realm_state validation in B4.3.1
The flow description has been amended, to remove the constraint on the Realm state. This change will be included in 1.1-alp10.
that is: ( the last line is removed)
D1.2.2 Realm Translation Table creation flow
Subsequent levels of RTT are added using the RMI_RTT_CREATE command.
(-) This can be performed when the state of the Realm is REALM_NEW or REALM_ACTIVE.

spec: feedback: Remove a failure condition

---

lib/vmsa/src/page_table.rs
rmm/src/allocator.rs
rmm/src/lib.rs
rmm/src/realm/context.rs
scripts/clippy.sh

This PR
- enables the `missing_safety_doc` rule of clippy.
- adds remain the remaining `Safety` notes.

clippy: Enable the missing_safety_doc rule

---

rmm/src/event/mainloop.rs
rmm/src/event/mod.rs
rmm/src/event/rmihandle.rs
rmm/src/event/rsihandle.rs
rmm/src/exception/trap.rs
rmm/src/host.rs
rmm/src/monitor.rs
rmm/src/realm/mm/rtt.rs
rmm/src/rmi/constraint.rs
rmm/src/rmi/features.rs
rmm/src/rmi/gpt.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/rec/exit.rs
rmm/src/rmi/rec/handlers.rs
rmm/src/rmi/rtt.rs
rmm/src/rmi/version.rs
rmm/src/rsi/constraint.rs
rmm/src/test_utils.rs

This PR
- refactors event handling logic
- removes temporary mapping for handling data abort (https://github.com/islet-project/islet/pull/394/commits/011e2fae1f740601579eb8c40d40d1a53bd2821d)
_NOTE: I will submit the PR for managing the Page Table as a pinned object separately, as it is experimental._
- RMM handles two types of events: RSI and RMI,
but RMI handler was located in the mainloop while RSI handler was part of RMM.
- The mainloop, created and managed by RMM, had a cyclic dependency
as the RMI handler in the mainloop referenced the monitor.
- Handling RMI in the mainloop also required locking the event queue,
leading to performance issues.
- Centralized both RMI and RSI event handlers within RMM for consistent event management.
- Refactored mainloop to only poll for RMI events, …

Refactor event handling logic & Handle the data abort case

---

examples/veraison/Makefile
examples/veraison/RUN.md
examples/veraison/realm-application/Cargo.toml
examples/veraison/reliant-party/Cargo.toml

Update Makefile, compiled tools directly from the git. Update README for the changes, some cosmetics.

Directly use repositories separated from remote-attestation

---

sdk/src/parser.rs

This PR fixes [the CI error](https://github.com/islet-project/islet/actions/runs/12064011930).
- SDK should return proper user data which is passed as realm challenge (simulated version)

sdk: Fix to return user_data on the simulated version

---

plat/fvp/memory.x
plat/fvp/src/entry.rs
plat/fvp/src/main.rs
rmm/src/config.rs
rmm/src/mm/translation.rs

This PR makes the first page of stack as the guard page (unmapped) to mitigate stack overflow.
The RMM memory layout assigns the CPU stacks in a continuous manner, which can lead to stack overflow issues spilling over between CPUs. 
```
| core 7 stack | core 6 stack | ... | core 0 stack |
^                 
stack_start 
(low addr)      >>>      (high addr)
```
To mitigate this, the first page of each stack is reserved as a guard page.
```
| guard_page | core 0 stack | guard_page | core 1 stack | ... | core 7 stack |
^                    
stack_start 
(low addr)      >>>      (high addr)
```

Add a guard page to mitigate stack overflow

---

lib/armv9a/Cargo.toml
lib/armv9a/src/regs.rs
lib/armv9a/src/regs/cptr_el2.rs
lib/armv9a/src/regs/id_aa64pfr1_el1.rs
lib/armv9a/src/regs/macros.rs
lib/armv9a/src/regs/smcr_el2.rs
lib/armv9a/src/regs/zcr_el1.rs
lib/armv9a/src/regs/zcr_el2.rs
plat/fvp/.cargo/config.toml
rmm/.cargo/config.toml
rmm/src/exception/trap.rs
rmm/src/exception/trap/syndrome.rs
rmm/src/exception/vectors.s
rmm/src/lib.rs
rmm/src/realm/context.rs
rmm/src/realm/rd.rs
rmm/src/rec.rs
rmm/src/rmi/features.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/realm/params.rs
rmm/src/simd.rs

1. exception: move non-volatile to volatile
- Move restore_nonvolatile_registers_from_rec_and_run  to restore_volatile_registers_from_rec_and_run.
- Make the func name short: from xxx_from_rec_and_run to xxx_from_rec.
2. rmi_features: use defined_bits() for feature register
- rmm: fpu contenxt management for realms
3. rmm: fpu contenxt management for realms
- save the fpu context on rec's exit if fpu is used during its runtime.
- resotre the fpu context on rec's first access to fpu since its recent REC_ENTER.

Realm FPU context

---

.gitmodules

I've created 4 repos for this:
`3rd-android-kernel`
`3rd-gki-build`
`3rd-linux` (for `nw-linux` and `realm-linux`)
`3rd-kvmtool` (for `kvmtool` and `kvmtool-rim-measurer`)
I didn't know the original repositories for the first two so they are just a copy&paste of the assets branch into main. More branches can be added in the future if required. For the latter two I've pushed some branches from the CCA upstream that we based our changes on.
The changed revision for `kvmtool-rim-measurer` is just a rebase to make the branches more consistent. It doesn't change any code.
I have not done `optee` as a dependency on this repository should be removed altogether. This will come later.
I've also marked most of the branches in the `assets` repository not to use them with an appropriate message where …

Update gitmodules for the islet-assets repo split

---

examples/confidential-ml/README.md

Resolves an issue where uppercase characters in documentation links caused incorrect navigation paths. Adjusted all link references to use lowercase

fix(link-redirection): ensure consistent lowercase paths for navigation

---

.gitignore
scripts/deps/pkgs.sh

Fixed the issue where running `./scripts/init.sh` fails on Ubuntu 24 due to the `externally-managed-environment` error, which arises from Ubuntu 24.04 systems preventing conflicts between system and user-managed Python packages.
Implemented a solution by creating a temporary Python virtual environment for the toml installation.
Updated .gitignore to exclude the venv folder to avoid tracking the virtual environment files.
- Raised the issue for review, as using a virtual environment for a single dependency may need further discussion.
- Open to suggestions for alternative solutions
Here is screenshot of error log

fix: resolve pip install toml error with virtual python env

---

.gitignore
scripts/config.py
scripts/init_android_on_qemu.sh
scripts/qemu-cca.py
scripts/run_qemu.sh

Use the following command to build & launch android on qemu: 
./script/init_android_on_qemu.sh
./scripts/qemu-cca.py -aosp
A number of patches for CCA support are applied to the host kernel. At the moment, it supports rmm-v1.0-eac5. But it'll be updated to the latest. 
It's the below branch in [islet-project/3rd-android-kernel:](https://github.com/islet-project/3rd-android-kernel/tree/common-android15-6.6/cca-host/rmm-v1.0-eac5)
common-android15-6.6/cca-host/rmm-v1.0-eac5
If the qemu is launched, you can see information about it like this: 
"The following lines contain useful debugging information:
Serial console is disabled; use -console=true to enable it.
Logcat output: /home/eom/cuttlefish/instances/cvd-1/logs/logcat
Kernel log: /home/eom/cuttlefish/instances/cvd-1/kernel.log
Launcher …

script: Add scripts to run AOSP on QEMU

---

.github/workflows/ci.yml

This PR fixes the [ci error](https://github.com/islet-project/islet/actions/runs/13190291462) related with actions version.
ref) https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

ci: Bump artifact actions to v4

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
rmm/Cargo.toml
rmm/fuzz/.cargo/config.toml
rmm/fuzz/Cargo.toml
rmm/fuzz/fuzz_targets/rmi_features_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_version_fuzz.rs
rmm/src/asm.rs
rmm/src/exception/trap.rs
rmm/src/granule/array/entry.rs
rmm/src/granule/array/mod.rs
rmm/src/lib.rs
rmm/src/mm/page_table/entry.rs
rmm/src/realm/mm/entry.rs
rmm/src/realm/mm/stage2_translation.rs
rmm/src/rec/context.rs
rmm/src/rec/simd.rs
rmm/src/rec/timer.rs
rmm/src/rmi/gpt.rs
rmm/src/rmi/rec/handlers.rs
scripts/fuzz-coverage.sh
scripts/fuzz.sh

(LFX Task 1)
This PR adds the initial fuzzing setup based on libfuzzer-sys along with two harnesses for RMI commands: FEATURES and VERSION.
Two scripts are provided:
1. `./scripts/fuzz.sh <fuzzer_name> <var_args>` - Runs the fuzzer. The script will run the fuzzer natively if the host is aarch64, otherwise it will fall back to QEMU userspace emulator.
2. `./scripts/fuzz-coverage.sh <fuzzer_name> <duration>` - Based on `./scripts/code-coverage.sh`, the fuzzer is run for a set duration and an html report is generated after at `./code-coverage/index.html`.

rmm: Initial fuzzing setup

---

rmm/fuzz/Cargo.toml
rmm/fuzz/fuzz_targets/rmi_data_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_data_create_unknown_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_granule_delegate_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_granule_undelegate_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_psci_complete_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_realm_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rec_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rec_enter_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_fold_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_init_ripas_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_map_unprotected_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_read_entry_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_set_ripas_fuzz.rs
rmm/src/granule/array/mod.rs
rmm/src/rmi/realm/mod.rs
rmm/src/rmi/rec/params.rs
rmm/src/rmi/rec/run.rs
rmm/src/test_utils.rs

(LFX Task 2)
This PR adds the following harnesses:
1. rmi_granule_delegate_fuzz: Fuzzes GRANULE_DELEGATE and GRANULE_UNDELEGATE
2. rmi_granule_undelegate_fuzz: Fuzzes invalid GRANULE_UNDELEGATE calls.
3. rmi_realm_create_fuzz: Fuzzes REALM_CREATE, REALM_ACTIVATE, and REALM_DESTROY (RealmParams)
4. rmi_rec_create_fuzz: Fuzzes REC_CREATE and REC_DESTROY (RecParams)
5. rmi_rtt_create_fuzz: Fuzzes RTT_CREATE and RTT_DESTROY
6. rmi_rtt_read_entry_fuzz: Fuzzes RTT_READ_ENTRY
7. rmi_data_create_fuzz: Fuzzes DATA_CREATE and DATA_DESTROY
8. rmi_data_create_unknown_fuzz: Fuzzes DATA_CREATE_UNKNOWN and DATA_DESTROY
9. rmi_rtt_map_unprotected_fuzz: Fuzzes RTT_MAP_UNPROTECTED and RTT_UNMAP_UNPROTECTED
10. rmi_rtt_init_ripas_fuzz: Fuzzes RTT_INIT_RIPAS
11. rmi_rtt_set_ripas_fuzz: Fuzzes RTT_SET_RIPAS …

rmm: Add more RMI fuzzing harnesses

---

rmm/src/realm/mm/rtt.rs

Currently, if RTT_SET_RIPAS were to be run on ASSIGNED_EMPTY RTTEs with the requested RIPAS being EMPTY, the HIPAS would unexpectedly change to UNASSIGNED. The expected behaviour is that the entry states should remain unchanged.
To fix this, the PR does the following:
1. Change the first case under the EMPTY request to handle UNASSIGNED_RAM instead of UNASSIGNED_EMPTY.
2. Add a fallback case which will handle both UNASSIGNED_EMPTY and ASSIGNED_EMPTY i.e the entries will be left unchanged.
This will hence mirror the code where the requested RIPAS is RAM instead.

realm/mm: Correct setting of RIPAS=EMPTY on ASSIGNED_EMPTY RTTEs

---

.gitmodules

This commit prepares for using 1.0-REL0 by updating TF-RMM (rmm-spec-v1.0-eac5 (2023-10-31) to [fdcf08](https://github.com/TF-RMM/tf-rmm/commit/fdcf08ed30527650f13151ea45e9601b1b125dca) (2024-09-17)) and TF-A (v2.10 to v2.11).
TF-RMM's rmm-spec-v1.0-rel0 branch (2024-10-03) has a compatibility issue, so this commit updates TF-RMM and TF-A which do not cause that issue.
[fdcf08](https://github.com/TF-RMM/tf-rmm/commit/fdcf08ed30527650f13151ea45e9601b1b125dca) is the last commit before the commit breaking a backward compatibility ([715ff8](https://github.com/TF-RMM/tf-rmm/commit/715ff8bd4a227890dd8e7849a4502c0ed6a26c44)).
According to [715ff8](https://github.com/TF-RMM/tf-rmm/commit/715ff8bd4a227890dd8e7849a4502c0ed6a26c44), it says that RMM would expect RMM-EL3 interface v0.3, but there …

Update TF-RMM and TF-A (v2.11)

---

.gitmodules

This PR updates submodules for `v1.0-rel0` alignment (see the below). TF-RMM now points to `rmm-spec-v1.0-rel0` tag, meaning that it contains all the features related to `v1.0-rel0`. With this version of TF-RMM, realm-linux can boot and most of ACS tests can pass (96 out of 100). It resolves the previous compatibility issue with ACS tests in #429 (https://github.com/TF-RMM/tf-rmm/commit/a2ef91da1ebcd451a978a6c9c07a39f865d4abf3) by using [the customized branch](https://github.com/islet-project/cca-rmm-acs/tree/islet-v1.0-rel0) for CCA-RMM-ACS. The customized branch cherry-picked all the commits whose commit messages contain REL0. We use this branch instead of `v1.0_REL0_12.24` tag, because `v1.0_REL0_12.24` tag includes plane-related features which are not relevant to `v1.0-rel0` and made …

Update submodules (v1.0-rel0)

---

.github/workflows/ci.yml
rmm/fuzz/fuzz_targets/rmi_data_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_data_create_unknown_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_features_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_granule_delegate_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_granule_undelegate_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_realm_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rec_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rec_enter_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_create_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_fold_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_rtt_map_unprotected_fuzz.rs
rmm/fuzz/fuzz_targets/rmi_version_fuzz.rs

With this PR, cargo fmt would be applied to all rust modules during CI checks, rather than rmm and fvp exclusively. This would prevent unformatted code in other modules (e.g., fuzz tests) from passing CI tests. To pass CI, it includes the previous @bokdeuk-jeong's commit of applying cargo fmt to fuzz tests.

ci: Apply cargo fmt to all

---

scripts/init_android_on_qemu.sh

This PR adds the missing mkdir command for `android_on_qemu` directory.

Add missing mkdir command in scripts/init_android_on_qemu.sh

---

scripts/fvp-cca

How host context in the normal world handled when switching to the realm world:
1. EL01 system registers and EL0 timer registers  (Scope of this PR)
Store/restore at the host before/after switching to/from the realm world.
2.  SIMD (already reflected in the islet rmm)
Store/restore simd at RMM for the nw host. 
SIMD has large register set and thus its context is managed only if necessary. 
As RMM knows when simd registers are used in the realm, RMM saves the host's simd context when necessary.
3. GIC (No need to be managed)
No need to be managed as RMM does not access it and realms access GIC as a virtual machine does.
4. Other EL2 system registers (Handled by EL3 during the world switch)
How to activate the code for the host context management:
- Provide as a kernel boot parameter. …

Add a new boot param,save_host_context, to the NW kernel

---

Cargo.toml
lib/uart/src/pl011.rs
plat/.cargo/config.toml
plat/Cargo.toml
plat/build.rs
plat/fvp/plat.rs
plat/qemu/memory.x
plat/qemu/plat.rs
plat/src/entry.rs
plat/src/main.rs
plat/src/plat.rs
rmm/Cargo.toml
rmm/src/config.rs
rmm/src/cpu.rs
rmm/src/event/mod.rs
rmm/src/granule/array/entry.rs
rmm/src/granule/array/mod.rs
rmm/src/granule/page_table/mod.rs
rmm/src/granule/page_table/translation.rs
rmm/src/lib.rs
rmm/src/mm/translation.rs
rmm/src/rmi/constraint.rs
rmm/src/rmm_el3/manifest.rs
rmm/src/rmm_el3/mod.rs
rmm/src/rsi/constraint.rs
scripts/fvp-cca
scripts/qemu-cca

1. Use manifest provided by the EL3 on RMM's boot
-  Move aarch64 common code in  plat/fvp/src to plat/src.
- Place fvp and qemu specific code in plat/fvp and plat/qemu.
- Get NS DRAM layout from the manifest provided by the EL3
on RMM's entry.
- granule : removed fvp specific dram layout
- mm : Use the el3-shared buf memory addr in layout
instead from the config.
- rmm_el3: removed hardcoded addr (RMM_SHARED_BUFFER_ADDR).
- TODO:   get the shared buf address holding the manifest from the rmm boot args (x3)
Leave it as out of the scope in this PR)
2.   cpuid: platform specific implementation
- Different affinity levels in mpidr_el1 are used in FVP and QEMU.
-  On FVP, mpidr_el1 is increased updating AFF1 and AFF1
0x81000000, 0x81000100, 0x81000200, 0x81000300...
-  On QEMU, AFF0 and AFF1 …

support for qemu

---

rmm/src/event/mod.rs
rmm/src/monitor.rs
rmm/src/rmi/constraint.rs

According to smccc,
registers X4-X17 must be preserved unless they contain results. Since X5-X17 and X18-X30 are preserved by EL3, preserve x4 only at RMM.
[Problem]
If nw-linux is configured with the 'defconfig' instead of the 'host' file, the host linux gives errors.
--------------------------NW log on launch_realm.sh----------------------------------
[   64.936201] Unable to handle kernel paging request at virtual address fffffdffbf000008
[   64.936729] Mem abort info:
[   64.936848]   ESR = 0x0000000096000006
[   64.936997]   EC = 0x25: DABT (current EL), IL = 32 bits
[   64.937164]   SET = 0, FnV = 0
[   64.937310]   EA = 0, S1PTW = 0
[   64.937445]   FSC = 0x06: level 2 translation fault
[   64.937606] Data abort info:
[   64.937737]   ISV = 0, ISS = 0x00000006, ISS2 = 0x00000000
[ …

smc: preserve x4 if unused

---

rmm/src/rmi/rtt.rs

Update out_desc check condition according to the changes made
to the state_unprot success condition for RMI_RTT_READ_ENTRY.
(Remove the shareability property.)
- CCAv1.0-eac5:
pre: walk.rtte.state == ASSIGNED_NS
post: (rtte.MemAttr == walk.rtte.MemAttr
&& rtte.S2AP == walk.rtte.S2AP
&& rtte.SH == walk.rtte.SH
&& rtte.addr == walk.rtte.addr)
- CCAv1.0-rel0
pre: walk.rtte.state == ASSIGNED_NS
post: (rtte.MemAttr == walk.rtte.MemAttr
&& rtte.S2AP == walk.rtte.S2AP
&& rtte.addr == walk.rtte.addr)

miri: re-enable rmi_rtt_map_unprotected_positive

---

plat/fvp/plat.rs
plat/qemu/plat.rs
plat/src/entry.rs
plat/src/main.rs
rmm/src/gic.rs
rmm/src/lib.rs
rmm/src/realm/rd.rs
rmm/src/rec/gic.rs
rmm/src/rec/simd.rs
rmm/src/rmi/features.rs
rmm/src/rmi/realm/params.rs
rmm/src/simd.rs

1.  gic, smid code split
There was an opinion that gic and simd are better kept out of the 'rec' directory in a previous PR.
To meet in the middle, I moved gic and simd code  which are independent from the realm context to the upper directory.
2. use boot arguments provided by EL2 on rmm entry
- x0: cpuid
- x1: version (unused)
- x2: total core count (unused)
- x3: shared buf containing manifest

Move rec independent code from rec

---

scripts/cca_base.py
scripts/fvp-cca
scripts/qemu-cca

1. Extract common code from fvp-cca and qemu-cca.
2. Define the code with a class, CCAPlatform. Each FVP and QEMU specific code is defined with FVPlatform and QEMUPlatform respectively.
Received tremendous help from a gen ai. More than 90% of code is generated by gen ai based on the existing code.

script: extract common code from fvp-cca and qemu-cca

---

.github/workflows/ci.yml
rmm/src/realm/mm/rtt.rs
rmm/src/rmi/features.rs
rmm/src/rmi/rec/run.rs
rmm/src/rmi/rtt.rs
rmm/src/rsi/mod.rs
rmm/src/rsi/ripas.rs

1. Misimplementation against Spec is fixed
- rtt: correct RMI_RTT_CREATE handler
Remove the condition, !parent_s2tte.is_assigned_ns(level - 1), which is not in the success or failure conditions for RMI_RTT_CREATE in the RMMv1.0-rel0 spec. 
(Fuzzer reached to this condition and triggered the assertion inside.)
-  correct RMI_FEATURES miri test
In case that the index input is zero, it should test if the output bits[42:63] is MBZ according to the spec.  (Current miri tests if bits[30:63] is MBZ)
2.  Use hard-coded feat_reg0 value for fuzzing. Otherwise, fuzzer crashes while it tries to initialize feat_reg0 with architecture specific values such as simd and gic.
Add 'fuzzing' to the lines in  #[cfg(not(any(miri, test)))])
3. Add #cfg to conditionally build functions only used for the fuzz …

Fix errors discoverd during the miri/fuzz test.

---

rmm/src/exception/trap.rs
rmm/src/rec/simd.rs

1. Fix save_state() for the fpu usage.
Saving fpu state for realm was accidentally missing.
2. Remove the redundant rec_simd.is_used check in save_state().
3. No side effect, but remove the redundant CPTR_EL2 register
configuration in the execption handler,
which is handled in restore_state_lazy().
Sorry for the trouble. Previous tests for the SVE/SME implementation was done on FVP with sve and sme hw features enabled. Tests for fpu were only partially tested and missed the error.
Error report from Lukasz,
```bash
$ ./scripts/fvp-cca --normal-world=linux --realm=linux --rmm=islet --rmm-log-level info
> ./launch-realm.sh
> cd /shared
> insmod rsi.ko
> ./bin/rsictl attest
> ./bin/rsictl attest
[  240.979467] rsi: device rsi open
[  240.988599] rsi: ioctl: attestation_token
[  240.988657] …
```

rec/simd: correct save_state()
